using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

class Program
{
    static void Main()
    {
        // Base directory (the folder where the executable runs)
        string baseDir = AppContext.BaseDirectory;

        // Folder containing the source DOCX files
        string inputFolder = Path.Combine(baseDir, "InputDocs");

        // Folder where the resulting TIFF files will be saved
        string outputFolder = Path.Combine(baseDir, "OutputTiffs");

        // Ensure both directories exist
        Directory.CreateDirectory(inputFolder);
        Directory.CreateDirectory(outputFolder);

        // If there are no DOCX files, create a sample document to demonstrate the process
        if (Directory.GetFiles(inputFolder, "*.docx").Length == 0)
        {
            var sampleDoc = new Document();
            var builder = new DocumentBuilder(sampleDoc);
            builder.Writeln("Sample document generated by the example.");
            string samplePath = Path.Combine(inputFolder, "Sample.docx");
            sampleDoc.Save(samplePath);
        }

        // Process each DOCX file in the input folder
        foreach (string docxPath in Directory.GetFiles(inputFolder, "*.docx"))
        {
            // Load the DOCX document
            Document doc = new Document(docxPath);

            // Configure TIFF save options
            ImageSaveOptions options = new ImageSaveOptions(SaveFormat.Tiff)
            {
                Resolution = 200,                         // Set DPI to 200
                TiffCompression = TiffCompression.Ccitt3 // Apply CCITT3 compression
            };

            // Build the output file name with .tiff extension
            string fileNameWithoutExt = Path.GetFileNameWithoutExtension(docxPath);
            string tiffPath = Path.Combine(outputFolder, fileNameWithoutExt + ".tiff");

            // Save the document as a TIFF image using the configured options
            doc.Save(tiffPath, options);
        }

        Console.WriteLine("Processing completed. TIFF files are located in:");
        Console.WriteLine(outputFolder);
    }
}
