using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

class BatchDocToTiff
{
    static void Main()
    {
        // Use folders relative to the executable directory.
        string baseDir = AppContext.BaseDirectory;
        string sourceFolder = Path.Combine(baseDir, "Input");
        string outputFolder = Path.Combine(baseDir, "Output");

        // Ensure both directories exist.
        Directory.CreateDirectory(sourceFolder);
        Directory.CreateDirectory(outputFolder);

        // If there are no Word files, create a simple sample document.
        if (Directory.GetFiles(sourceFolder, "*.*", SearchOption.TopDirectoryOnly).Length == 0)
        {
            var sampleDoc = new Document();
            var builder = new DocumentBuilder(sampleDoc);
            builder.Writeln("This is a sample document generated by the example.");
            string samplePath = Path.Combine(sourceFolder, "Sample.docx");
            sampleDoc.Save(samplePath);
        }

        // Get all Word documents in the source folder (DOC and DOCX).
        string[] docFiles = Directory.GetFiles(sourceFolder, "*.*", SearchOption.TopDirectoryOnly);
        foreach (string filePath in docFiles)
        {
            // Process only .doc and .docx files.
            string ext = Path.GetExtension(filePath).ToLowerInvariant();
            if (ext != ".doc" && ext != ".docx")
                continue;

            // Load the document.
            Document doc = new Document(filePath);

            // Configure image save options for TIFF with CCITT4 compression and 1‑bit per pixel.
            ImageSaveOptions options = new ImageSaveOptions(SaveFormat.Tiff)
            {
                TiffCompression = TiffCompression.Ccitt4,
                PixelFormat = ImagePixelFormat.Format1bppIndexed,
                TiffBinarizationMethod = ImageBinarizationMethod.Threshold,
                PageLayout = MultiPageLayout.TiffFrames()
            };

            // Build the output file name (same base name, .tiff extension).
            string outputFile = Path.Combine(outputFolder, Path.GetFileNameWithoutExtension(filePath) + ".tiff");

            // Save the document as a TIFF file.
            doc.Save(outputFile, options);
        }

        Console.WriteLine($"Conversion completed. TIFF files are located in: {outputFolder}");
    }
}
