using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Define a folder to watch for new DOCX files.
        string watchFolder = Path.Combine(Directory.GetCurrentDirectory(), "WatchFolder");
        Directory.CreateDirectory(watchFolder);

        // Create a sample DOCX file in the watch folder.
        string sampleDocx = Path.Combine(watchFolder, "Sample.docx");
        Document sampleDocument = new Document();
        DocumentBuilder builder = new DocumentBuilder(sampleDocument);
        builder.Writeln("This is a sample document generated by Aspose.Words.");
        sampleDocument.Save(sampleDocx);

        // Convert each DOCX file in the folder to a multipage TIFF.
        foreach (string docxPath in Directory.GetFiles(watchFolder, "*.docx"))
        {
            // Load the DOCX file.
            Document doc = new Document(docxPath);

            // Prepare TIFF save options.
            ImageSaveOptions tiffOptions = new ImageSaveOptions(SaveFormat.Tiff);
            // Optional: set compression (default is Lzw).
            // tiffOptions.TiffCompression = TiffCompression.Lzw;

            // Determine the output TIFF file name.
            string tiffPath = Path.ChangeExtension(docxPath, ".tiff");

            // Save the document as a TIFF image (all pages are rendered into a single multipage TIFF).
            doc.Save(tiffPath, tiffOptions);

            // Verify that the TIFF file was created.
            if (!File.Exists(tiffPath))
                throw new InvalidOperationException($"Failed to create TIFF file: {tiffPath}");
        }

        // The program finishes here without waiting for user input.
    }
}
