using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Define directories for input documents, output TIFFs, and the PowerShell script.
        string baseDir = Path.Combine(Directory.GetCurrentDirectory(), "DemoData");
        string inputDir = Path.Combine(baseDir, "InputDocs");
        string outputDir = Path.Combine(baseDir, "OutputTiffs");
        string scriptDir = Path.Combine(baseDir, "Scripts");

        // Ensure all directories exist.
        Directory.CreateDirectory(inputDir);
        Directory.CreateDirectory(outputDir);
        Directory.CreateDirectory(scriptDir);

        // -----------------------------------------------------------------
        // 1. Create a sample DOC file that the PowerShell script will process.
        // -----------------------------------------------------------------
        string sampleDocPath = Path.Combine(inputDir, "SampleDocument.doc");
        Document sampleDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(sampleDoc);
        builder.Writeln("This is a sample document generated by Aspose.Words.");
        // Save as legacy DOC format to match the *.doc filter used in the script.
        sampleDoc.Save(sampleDocPath, SaveFormat.Doc);

        // -----------------------------------------------------------------
        // 2. Prepare the PowerShell script content.
        // -----------------------------------------------------------------
        string scriptPath = Path.Combine(scriptDir, "ConvertDocsToTiff.ps1");
        string scriptContent = $@"
# PowerShell script to convert DOC files to TIFF with 250 DPI using Aspose.Words
param(
    [string]$inputFolder = '{inputDir.Replace("\\", "\\\\")}',
    [string]$outputFolder = '{outputDir.Replace("\\", "\\\\")}'
)

# Ensure the output folder exists.
if (-not (Test-Path $outputFolder)) {{
    New-Item -ItemType Directory -Path $outputFolder | Out-Null
}}

# Load the Aspose.Words assembly (assumes the DLL is placed next to this script).
Add-Type -Path '{Path.Combine(scriptDir, "Aspose.Words.dll").Replace("\\", "\\\\")}'

# Iterate over each .doc file in the input folder.
foreach ($file in Get-ChildItem -Path $inputFolder -Filter *.doc) {{
    $doc = New-Object Aspose.Words.Document $file.FullName
    $options = New-Object Aspose.Words.Saving.ImageSaveOptions([Aspose.Words.SaveFormat]::Tiff)
    $options.Resolution = 250
    $outputPath = Join-Path $outputFolder ($file.BaseName + '.tiff')
    $doc.Save($outputPath, $options)
}}
".TrimStart();

        // Write the script to disk.
        File.WriteAllText(scriptPath, scriptContent);

        // -----------------------------------------------------------------
        // 3. Copy the Aspose.Words DLL next to the script so it can be loaded.
        // -----------------------------------------------------------------
        string assemblyPath = typeof(Document).Assembly.Location;
        string targetDllPath = Path.Combine(scriptDir, Path.GetFileName(assemblyPath));
        File.Copy(assemblyPath, targetDllPath, overwrite: true);

        // -----------------------------------------------------------------
        // 4. Validate that the script and DLL were created successfully.
        // -----------------------------------------------------------------
        if (!File.Exists(scriptPath))
            throw new FileNotFoundException("PowerShell script was not created.", scriptPath);
        if (!File.Exists(targetDllPath))
            throw new FileNotFoundException("Aspose.Words.dll was not copied.", targetDllPath);

        // Inform the user (via console) that the setup is complete.
        Console.WriteLine("Setup complete.");
        Console.WriteLine($"- Sample DOC: {sampleDocPath}");
        Console.WriteLine($"- PowerShell script: {scriptPath}");
        Console.WriteLine($"- Aspose.Words DLL: {targetDllPath}");
        Console.WriteLine("Run the PowerShell script to convert DOC files to TIFF at 250 DPI.");
    }
}
