using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Define directories for sample documents and the PowerShell script.
        string baseDir = Path.Combine(Directory.GetCurrentDirectory(), "RenderDemo");
        string docsDir = Path.Combine(baseDir, "InputDocs");
        string scriptPath = Path.Combine(baseDir, "ConvertDocsToTiff.ps1");

        // Ensure clean environment.
        if (Directory.Exists(baseDir))
            Directory.Delete(baseDir, true);
        Directory.CreateDirectory(docsDir);

        // Create a few sample DOC files.
        CreateSampleDoc(Path.Combine(docsDir, "Sample1.doc"), "This is the first sample document.");
        CreateSampleDoc(Path.Combine(docsDir, "Sample2.doc"), "This is the second sample document.");

        // Generate PowerShell script content.
        string scriptContent = $@"
# Load Aspose.Words assembly (assumes Aspose.Words.dll is located in the same folder as this script).
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$assemblyPath = Join-Path $scriptDir 'Aspose.Words.dll'
Add-Type -Path $assemblyPath

# Define the folder containing DOC files.
$docsFolder = '{EscapePowerShellString(docsDir)}'

# Iterate over each .doc file in the folder.
Get-ChildItem -Path $docsFolder -Filter *.doc | ForEach-Object {{
    $docPath = $_.FullName
    $outputPath = Join-Path $docsFolder ($_.BaseName + '.tiff')

    # Load the document.
    $document = New-Object Aspose.Words.Document($docPath)

    # Configure image save options: set DPI (Resolution) to 250.
    $options = New-Object Aspose.Words.Saving.ImageSaveOptions([Aspose.Words.SaveFormat]::Tiff)
    $options.Resolution = 250

    # Save as TIFF.
    $document.Save($outputPath, $options)
}}
";

        // Write the script to file.
        File.WriteAllText(scriptPath, scriptContent);

        // Validate that the script file was created.
        if (!File.Exists(scriptPath))
            throw new Exception("Failed to create the PowerShell script.");

        // Optionally, validate that the sample TIFF files can be generated by invoking the script.
        // This step is omitted to keep the example self‑contained and non‑interactive.
    }

    // Helper method to create a simple DOC file with given text.
    private static void CreateSampleDoc(string filePath, string text)
    {
        Document doc = new Document();
        DocumentBuilder builder = new DocumentBuilder(doc);
        builder.Writeln(text);
        doc.Save(filePath, SaveFormat.Doc);
    }

    // Escapes single quotes for PowerShell string literals.
    private static string EscapePowerShellString(string path)
    {
        return path.Replace("'", "''");
    }
}
