using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Create a simple document with some text.
        Document doc = new Document();
        DocumentBuilder builder = new DocumentBuilder(doc);
        builder.Font.Name = "Times New Roman";
        builder.Font.Size = 24;
        builder.Writeln("This is a high‑resolution TIFF image generated by Aspose.Words.");

        // Prepare the output folder.
        string outputDir = Path.Combine(Directory.GetCurrentDirectory(), "Output");
        Directory.CreateDirectory(outputDir);

        // Define the output TIFF file path.
        string tiffPath = Path.Combine(outputDir, "HighResolution.tiff");

        // Configure image save options for TIFF with 300 DPI resolution.
        ImageSaveOptions options = new ImageSaveOptions(SaveFormat.Tiff)
        {
            Resolution = 300 // Sets both horizontal and vertical DPI.
        };

        // Save the document pages as a TIFF image.
        doc.Save(tiffPath, options);

        // Verify that the TIFF file was created.
        if (!File.Exists(tiffPath))
            throw new InvalidOperationException("Failed to create the TIFF image.");

        // Optionally, inform the user (no interactive wait required).
        Console.WriteLine($"TIFF image saved successfully at: {tiffPath}");
    }
}
