using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Define output folder and file.
        string artifactsDir = Path.Combine(Directory.GetCurrentDirectory(), "Artifacts");
        Directory.CreateDirectory(artifactsDir);
        string outputPath = Path.Combine(artifactsDir, "HighResolution.tiff");

        // Create a simple document.
        Document doc = new Document();
        DocumentBuilder builder = new DocumentBuilder(doc);
        builder.Font.Name = "Times New Roman";
        builder.Font.Size = 24;
        builder.Writeln("This is a high‑resolution TIFF image generated by Aspose.Words.");

        // Configure image save options for TIFF with 600 DPI.
        ImageSaveOptions options = new ImageSaveOptions(SaveFormat.Tiff)
        {
            // Set both horizontal and vertical resolution to 600 DPI.
            HorizontalResolution = 600f,
            VerticalResolution = 600f
            // Alternatively, options.Resolution = 600f; // sets both.
        };

        // Save the document as a TIFF image.
        doc.Save(outputPath, options);

        // Verify that the file was created.
        if (!File.Exists(outputPath))
            throw new FileNotFoundException("The TIFF file was not created.", outputPath);

        // Optionally, report success (no console input required).
        Console.WriteLine("TIFF file saved successfully at: " + outputPath);
    }
}
