using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Aspose.Words;
using Aspose.Words.Reporting;

public class Program
{
    public static void Main()
    {
        // Paths for the template and the generated report.
        const string templatePath = "Template.docx";
        const string reportPath = "Report.docx";

        // -----------------------------------------------------------------
        // 1. Create a simple template document with a foreach tag.
        // -----------------------------------------------------------------
        Document templateDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(templateDoc);
        builder.Writeln("Report generated by Aspose.Words ReportingEngine");
        builder.Writeln("<<foreach [items]>>");
        builder.Writeln("Name: <<[Name]>>, Value: <<[Value]>>");
        builder.Writeln("<</foreach>>");
        templateDoc.Save(templatePath);

        // -----------------------------------------------------------------
        // 2. Load the template document.
        // -----------------------------------------------------------------
        Document reportDoc = new Document(templatePath);

        // -----------------------------------------------------------------
        // 3. Prepare a cancellation token that will be triggered after a short delay.
        // -----------------------------------------------------------------
        var cts = new CancellationTokenSource();
        // Cancel after 100 milliseconds to simulate user abort.
        Task.Run(async () =>
        {
            await Task.Delay(100);
            cts.Cancel();
        });

        // -----------------------------------------------------------------
        // 4. Build a large data source using LINQ.
        //    The query checks token.IsCancellationRequested on each iteration
        //    and throws OperationCanceledException when cancellation is requested.
        // -----------------------------------------------------------------
        var items = Enumerable.Range(1, 1_000_000).Select(i =>
        {
            if (cts.Token.IsCancellationRequested)
                throw new OperationCanceledException("Report generation was canceled.");
            return new { Name = $"Item{i}", Value = i };
        });

        // -----------------------------------------------------------------
        // 5. Run the reporting engine with the data source.
        // -----------------------------------------------------------------
        ReportingEngine engine = new ReportingEngine();

        try
        {
            // The data source name ("items") matches the tag used in the template.
            engine.BuildReport(reportDoc, items, "items");

            // Save the generated report if the build completes.
            reportDoc.Save(reportPath);
            Console.WriteLine($"Report successfully generated: {Path.GetFullPath(reportPath)}");
        }
        catch (OperationCanceledException ex)
        {
            // Expected path when the token is cancelled.
            Console.WriteLine(ex.Message);
        }
        catch (Exception ex)
        {
            // Any other unexpected errors.
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
