using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Aspose.Words;
using Aspose.Words.Reporting;

public class Item
{
    public string Name { get; set; }
    public int Value { get; set; }
}

// IEnumerable wrapper that aborts enumeration when the cancellation token is set.
public class CancellableEnumerable<T> : IEnumerable<T>
{
    private readonly IEnumerable<T> _source;
    private readonly CancellationToken _token;

    public CancellableEnumerable(IEnumerable<T> source, CancellationToken token)
    {
        _source = source;
        _token = token;
    }

    public IEnumerator<T> GetEnumerator()
    {
        foreach (var item in _source)
        {
            if (_token.IsCancellationRequested)
                throw new OperationCanceledException("Report generation was canceled.");

            yield return item;
        }
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}

public class Program
{
    public static void Main()
    {
        // Create a simple template document for the ReportingEngine.
        Document template = new Document();
        DocumentBuilder builder = new DocumentBuilder(template);
        builder.Writeln("Report generated by Aspose.Words ReportingEngine");
        // Correct foreach syntax.
        builder.Writeln("<<foreach [in items]>>");
        builder.Writeln("Name: <<[Name]>>, Value: <<[Value]>>");
        builder.Writeln("<</foreach>>");

        // Prepare a large data source.
        List<Item> data = Enumerable.Range(1, 10000)
            .Select(i => new Item { Name = $"Item{i}", Value = i })
            .ToList();

        // Set up a cancellation token that will be triggered shortly after the report starts.
        CancellationTokenSource cts = new CancellationTokenSource();

        // Cancel after a short delay (e.g., 10 milliseconds) to simulate aborting a large report.
        Task.Run(() =>
        {
            Thread.Sleep(10);
            cts.Cancel();
        });

        // Wrap the data source so that enumeration checks the token.
        var cancellableData = new CancellableEnumerable<Item>(data, cts.Token);

        // Build the report using the ReportingEngine.
        ReportingEngine engine = new ReportingEngine();

        try
        {
            // The third argument is the name used inside the template.
            engine.BuildReport(template, cancellableData, "items");

            // Save the completed report.
            string outputPath = Path.Combine(Directory.GetCurrentDirectory(), "Report.docx");
            template.Save(outputPath);
            Console.WriteLine($"Report generated successfully: {outputPath}");
        }
        catch (InvalidOperationException ex) when (ex.InnerException is OperationCanceledException)
        {
            // The ReportingEngine wraps the cancellation exception; handle it here.
            string canceledPath = Path.Combine(Directory.GetCurrentDirectory(), "Report_Canceled.docx");
            template.Save(canceledPath);
            Console.WriteLine($"Report generation aborted: {ex.InnerException.Message}");
            Console.WriteLine($"Partial report saved to: {canceledPath}");
        }
        catch (OperationCanceledException ex)
        {
            // Fallback in case the engine does not wrap the exception.
            string canceledPath = Path.Combine(Directory.GetCurrentDirectory(), "Report_Canceled.docx");
            template.Save(canceledPath);
            Console.WriteLine($"Report generation aborted: {ex.Message}");
            Console.WriteLine($"Partial report saved to: {canceledPath}");
        }
    }
}
