using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Loading;
using Aspose.Words.Saving;

public class Program
{
    // Simulates obtaining a DOCX document from a web service.
    private static Document GetDocumentFromWebService()
    {
        Document doc = new Document();
        DocumentBuilder builder = new DocumentBuilder(doc);
        builder.Writeln("Content generated by the simulated web service.");
        return doc;
    }

    public static void Main()
    {
        // Prepare output folder.
        string outputDir = Path.Combine(Path.GetTempPath(), "AsposeJoinExample");
        Directory.CreateDirectory(outputDir);

        // File paths.
        string baseDocPath = Path.Combine(outputDir, "BaseDocument.docx");
        string mergedDocPath = Path.Combine(outputDir, "MergedDocument.docx");
        string pdfPath = Path.Combine(outputDir, "MergedDocument.pdf");

        // -----------------------------------------------------------------
        // 1. Create the existing (base) DOCX document.
        // -----------------------------------------------------------------
        Document baseDoc = new Document();
        DocumentBuilder baseBuilder = new DocumentBuilder(baseDoc);
        baseBuilder.Writeln("Base document content.");
        baseDoc.Save(baseDocPath);

        // -----------------------------------------------------------------
        // 2. Obtain the DOCX generated from a web service.
        // -----------------------------------------------------------------
        Document webDoc = GetDocumentFromWebService();

        // -----------------------------------------------------------------
        // 3. Append the web‑service document to the base document.
        // -----------------------------------------------------------------
        baseDoc.AppendDocument(webDoc, ImportFormatMode.KeepSourceFormatting);

        // Save the merged DOCX.
        baseDoc.Save(mergedDocPath);

        // -----------------------------------------------------------------
        // 4. Convert the merged document to PDF and encrypt it with a password.
        // -----------------------------------------------------------------
        const string userPassword = "UserPassword";
        PdfEncryptionDetails encryption = new PdfEncryptionDetails(userPassword, string.Empty);
        PdfSaveOptions pdfOptions = new PdfSaveOptions { EncryptionDetails = encryption };
        baseDoc.Save(pdfPath, pdfOptions);

        // -----------------------------------------------------------------
        // 5. Validate that the output files were created.
        // -----------------------------------------------------------------
        if (!File.Exists(mergedDocPath) || !File.Exists(pdfPath))
            throw new InvalidOperationException("One or more output files were not created.");

        // -----------------------------------------------------------------
        // 6. Verify that the PDF is encrypted (loading without a password must fail).
        // -----------------------------------------------------------------
        try
        {
            // Attempt to load the encrypted PDF without providing a password.
            Document _ = new Document(pdfPath);
            // If no exception is thrown, the PDF is not encrypted as expected.
            throw new InvalidOperationException("PDF encryption verification failed: the document opened without a password.");
        }
        catch (IncorrectPasswordException)
        {
            // Expected outcome – the PDF is correctly encrypted.
        }

        // The example finishes without requiring any user interaction.
    }
}
