using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Define file paths.
        string outputDir = Path.Combine(Directory.GetCurrentDirectory(), "Output");
        Directory.CreateDirectory(outputDir);

        string existingDocPath = Path.Combine(outputDir, "Existing.docx");
        string mergedDocPath = Path.Combine(outputDir, "Merged.docx");
        string finalPdfPath = Path.Combine(outputDir, "Final.pdf");

        // -----------------------------------------------------------------
        // 1. Create an existing DOCX file locally.
        // -----------------------------------------------------------------
        Document existingDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(existingDoc);
        builder.Writeln("This is the content of the existing document.");
        existingDoc.Save(existingDocPath);

        // -----------------------------------------------------------------
        // 2. Simulate a DOCX obtained from a REST API.
        //    Here we create the document in memory and store it in a stream.
        // -----------------------------------------------------------------
        Document restDoc = new Document();
        DocumentBuilder restBuilder = new DocumentBuilder(restDoc);
        restBuilder.Writeln("This content was generated by a simulated REST API.");
        using (MemoryStream restStream = new MemoryStream())
        {
            // Save the simulated REST document as DOCX into the stream.
            restDoc.Save(restStream, SaveFormat.Docx);
            // Reset the stream position before loading.
            restStream.Position = 0;

            // Load the document from the stream as if it were received from the API.
            Document restDocFromStream = new Document(restStream);

            // -----------------------------------------------------------------
            // 3. Append the REST‑generated document to the existing document.
            // -----------------------------------------------------------------
            existingDoc.AppendDocument(restDocFromStream, ImportFormatMode.KeepSourceFormatting);
        }

        // Save the merged result as DOCX (optional, useful for verification).
        existingDoc.Save(mergedDocPath);

        // -----------------------------------------------------------------
        // 4. Convert the merged document to PDF and encrypt it with a password.
        // -----------------------------------------------------------------
        PdfSaveOptions pdfOptions = new PdfSaveOptions
        {
            // User password required to open the PDF; owner password can be used for permissions.
            EncryptionDetails = new PdfEncryptionDetails("UserPassword123", "OwnerPassword123")
        };
        existingDoc.Save(finalPdfPath, pdfOptions);

        // -----------------------------------------------------------------
        // 5. Validate that the output files were created.
        // -----------------------------------------------------------------
        if (!File.Exists(mergedDocPath))
            throw new InvalidOperationException($"Merged DOCX was not created at '{mergedDocPath}'.");
        if (!File.Exists(finalPdfPath))
            throw new InvalidOperationException($"Encrypted PDF was not created at '{finalPdfPath}'.");

        // The program finishes without waiting for user input.
    }
}
