using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Prepare output directory.
        string outputDir = Path.Combine(Directory.GetCurrentDirectory(), "Output");
        Directory.CreateDirectory(outputDir);

        // -----------------------------------------------------------------
        // 1. Create the destination DOCX (simulating an existing document).
        // -----------------------------------------------------------------
        Document destinationDoc = new Document();
        DocumentBuilder destBuilder = new DocumentBuilder(destinationDoc);
        destBuilder.Writeln("This is the original document content.");

        // -----------------------------------------------------------------
        // 2. Simulate a DOCX generated by a web service.
        //    Create it in memory and load it from a stream.
        // -----------------------------------------------------------------
        Document webDoc = new Document();
        DocumentBuilder webBuilder = new DocumentBuilder(webDoc);
        webBuilder.Writeln("Content received from a web service.");

        using (MemoryStream webStream = new MemoryStream())
        {
            // Save the web-generated document to the stream as DOCX.
            webDoc.Save(webStream, SaveFormat.Docx);
            webStream.Position = 0; // Reset before loading.

            // Load the document from the stream.
            Document webDocFromStream = new Document(webStream);

            // -------------------------------------------------------------
            // 3. Append the web-generated document to the destination.
            // -------------------------------------------------------------
            destinationDoc.AppendDocument(webDocFromStream, ImportFormatMode.KeepSourceFormatting);
        }

        // -----------------------------------------------------------------
        // 4. Save the merged document as an encrypted PDF.
        // -----------------------------------------------------------------
        string pdfPath = Path.Combine(outputDir, "MergedEncrypted.pdf");
        PdfSaveOptions pdfOptions = new PdfSaveOptions
        {
            // Set user password; owner password can be left empty if not needed.
            EncryptionDetails = new PdfEncryptionDetails("UserPassword123", string.Empty)
        };
        destinationDoc.Save(pdfPath, pdfOptions);

        // -----------------------------------------------------------------
        // 5. Validate that the PDF file was created.
        // -----------------------------------------------------------------
        if (!File.Exists(pdfPath))
            throw new InvalidOperationException("The encrypted PDF was not created.");

        // Optional validation: attempt to open without a password to ensure encryption.
        try
        {
            // This should throw IncorrectPasswordException because the PDF is protected.
            Document testLoad = new Document(pdfPath);
            // If no exception, the PDF is not encrypted as expected.
            throw new InvalidOperationException("The PDF is not password protected as expected.");
        }
        catch (IncorrectPasswordException)
        {
            // Expected outcome – the PDF is encrypted.
        }

        // The program finishes without requiring any user interaction.
    }
}
