using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Replacing;

public class Program
{
    public static void Main()
    {
        // Define file paths in the current directory.
        string originalPath = Path.Combine(Directory.GetCurrentDirectory(), "original.docx");
        string revisedPath = Path.Combine(Directory.GetCurrentDirectory(), "revised.docx");

        // -----------------------------------------------------------------
        // 1. Create a sample document with placeholder text.
        // -----------------------------------------------------------------
        Document doc = new Document();
        DocumentBuilder builder = new DocumentBuilder(doc);
        builder.Writeln("This is a sample document.");
        builder.Writeln("Find and replace the word {placeholder} in this line.");
        doc.Save(originalPath);

        // -----------------------------------------------------------------
        // 2. Load the document, enable track changes, and perform replace.
        // -----------------------------------------------------------------
        Document loadedDoc = new Document(originalPath);
        loadedDoc.StartTrackRevisions("Demo Author", DateTime.Now);

        // Perform a find-and-replace operation while tracking is enabled.
        // Use FindReplaceOptions to specify case‑insensitive whole‑word matching.
        FindReplaceOptions options = new FindReplaceOptions
        {
            MatchCase = false,
            FindWholeWordsOnly = true
        };
        loadedDoc.Range.Replace("{placeholder}", "Aspose.Words", options);

        loadedDoc.StopTrackRevisions();

        // -----------------------------------------------------------------
        // 3. List all generated revisions.
        // -----------------------------------------------------------------
        Console.WriteLine("Revisions generated by the find-and-replace operation:");
        foreach (Revision rev in loadedDoc.Revisions)
        {
            string text = rev.ParentNode != null ? rev.ParentNode.GetText().Trim() : "<no parent node>";
            Console.WriteLine($"- Type: {rev.RevisionType}, Author: {rev.Author}, Date: {rev.DateTime}, Text: \"{text}\"");
        }

        // -----------------------------------------------------------------
        // 4. Save the revised document.
        // -----------------------------------------------------------------
        loadedDoc.Save(revisedPath);
    }
}
