using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

class TiffToJpegBatchConverter
{
    static void Main()
    {
        // Use directories relative to the executable location.
        string baseDir = AppContext.BaseDirectory;
        string inputDirectory = Path.Combine(baseDir, "InputTiffs");
        string outputDirectory = Path.Combine(baseDir, "OutputJpegs");

        // Ensure both directories exist.
        Directory.CreateDirectory(inputDirectory);
        Directory.CreateDirectory(outputDirectory);

        // If there are no TIFF files, create a sample one for demonstration using Aspose.Words.
        if (Directory.GetFiles(inputDirectory, "*.tif*").Length == 0)
        {
            string sampleTiffPath = Path.Combine(inputDirectory, "sample.tif");
            Document sampleDoc = new Document();
            DocumentBuilder builder = new DocumentBuilder(sampleDoc);
            builder.Writeln("Sample TIFF generated by Aspose.Words.");
            ImageSaveOptions tiffOptions = new ImageSaveOptions(SaveFormat.Tiff);
            sampleDoc.Save(sampleTiffPath, tiffOptions);
        }

        // Iterate over all TIFF files in the input directory.
        foreach (string tiffFilePath in Directory.GetFiles(inputDirectory, "*.tif*"))
        {
            // Create a new empty Word document.
            Document doc = new Document();

            // Insert the TIFF image into the document.
            DocumentBuilder builder = new DocumentBuilder(doc);
            builder.InsertImage(tiffFilePath);

            // Configure image save options for JPEG with 90% quality.
            ImageSaveOptions jpegOptions = new ImageSaveOptions(SaveFormat.Jpeg)
            {
                JpegQuality = 90
            };

            // Build the output JPEG file path.
            string jpegFileName = Path.GetFileNameWithoutExtension(tiffFilePath) + ".jpg";
            string jpegFilePath = Path.Combine(outputDirectory, jpegFileName);

            // Save the document as a JPEG image using the configured options.
            doc.Save(jpegFilePath, jpegOptions);
        }

        Console.WriteLine($"Conversion complete. JPEG files are located in: {outputDirectory}");
    }
}
