using System;
using System.IO;
using System.Threading.Tasks;
using Aspose.Words;
using Aspose.Words.Saving;

class Program
{
    static async Task Main()
    {
        const string templatePath = "Template.docx";
        const string outputPdfPath = "Result.pdf";

        // Ensure a template exists.
        if (!File.Exists(templatePath))
        {
            var tempDoc = new Document();
            var tempBuilder = new DocumentBuilder(tempDoc);
            tempBuilder.Writeln("Document generated by the sample program.");
            tempBuilder.StartBookmark("Image1");
            tempBuilder.Writeln("Bookmark for the first image.");
            tempBuilder.EndBookmark("Image1");
            tempDoc.Save(templatePath);
        }

        // Load the template document.
        var doc = new Document(templatePath);
        var builder = new DocumentBuilder(doc);

        // Insert the first image at a bookmark named "Image1".
        await InsertSampleImageAsync(builder, "Image1");

        // Insert the second image at the end of the document (no bookmark).
        await InsertSampleImageAsync(builder, null);

        // Save the modified document as PDF.
        doc.Save(outputPdfPath, SaveFormat.Pdf);
    }

    // Inserts a sample PNG image (generated from an embedded base‑64 string) into the document.
    // If bookmarkName is provided, the cursor is moved to that bookmark before insertion.
    static async Task InsertSampleImageAsync(DocumentBuilder builder, string bookmarkName)
    {
        // Simulate async work.
        await Task.Yield();

        if (!string.IsNullOrEmpty(bookmarkName))
            builder.MoveToBookmark(bookmarkName);

        // A tiny 1x1 red PNG encoded in base‑64.
        const string base64Png = 
            "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+XK2UAAAAASUVORK5CYII=";
        byte[] imageBytes = Convert.FromBase64String(base64Png);

        // Insert the image (inline, 100 % scale).
        builder.InsertImage(imageBytes);
    }
}
