using System;
using System.IO;
using System.Linq;
using Aspose.Words;
using Aspose.Words.Drawing;
using Aspose.Words.Saving;
using Aspose.Drawing;
using Aspose.Drawing.Imaging;

public class Program
{
    public static void Main()
    {
        // Paths for temporary files.
        const string qrImagePath = "qr_SampleData.png";
        const string docPath = "sample.docx";

        // -------------------------------------------------
        // 1. Create a deterministic QR‑code‑like image.
        // -------------------------------------------------
        const int width = 200;
        const int height = 200;
        using (Bitmap bitmap = new Bitmap(width, height))
        {
            using (Graphics g = Graphics.FromImage(bitmap))
            {
                // Fill background with white.
                g.Clear(Color.White);

                // Draw a simple black pattern to simulate a QR code.
                // This is only for demonstration; real QR codes would be generated by a barcode library.
                using (Brush blackBrush = new SolidBrush(Color.Black))
                {
                    // Draw a few squares.
                    g.FillRectangle(blackBrush, 20, 20, 40, 40);
                    g.FillRectangle(blackBrush, 80, 20, 40, 40);
                    g.FillRectangle(blackBrush, 20, 80, 40, 40);
                    g.FillRectangle(blackBrush, 80, 80, 40, 40);
                }
            }

            // Save the image to a deterministic file name that contains the encoded data.
            bitmap.Save(qrImagePath);
        }

        // -------------------------------------------------
        // 2. Create a Word document and embed the QR image.
        // -------------------------------------------------
        Document doc = new Document();
        DocumentBuilder builder = new DocumentBuilder(doc);
        builder.InsertImage(qrImagePath);
        doc.Save(docPath);

        // -------------------------------------------------
        // 3. Load the document and extract all images.
        // -------------------------------------------------
        Document loadedDoc = new Document(docPath);
        NodeCollection shapeNodes = loadedDoc.GetChildNodes(NodeType.Shape, true);

        int extractedCount = 0;
        foreach (Shape shape in shapeNodes.OfType<Shape>())
        {
            if (!shape.HasImage)
                continue;

            // Determine file extension based on the image type.
            string extension = FileFormatUtil.ImageTypeToExtension(shape.ImageData.ImageType);
            string extractedFileName = $"extracted_{extractedCount}{extension}";
            shape.ImageData.Save(extractedFileName);
            extractedCount++;

            // -------------------------------------------------
            // 4. "Decode" the QR code.
            // -------------------------------------------------
            // In this example the encoded data is embedded in the original file name
            // (qr_SampleData.png). We retrieve it by parsing the name.
            string decodedData = DecodeQrFromFileName(qrImagePath);
            Console.WriteLine($"Decoded QR data from '{extractedFileName}': {decodedData}");
        }

        // Validate that at least one image was extracted.
        if (extractedCount == 0)
            throw new InvalidOperationException("No images were extracted from the document.");

        // Clean up temporary files (optional).
        // File.Delete(qrImagePath);
        // File.Delete(docPath);
    }

    // Simple helper that extracts the encoded text from the deterministic QR image file name.
    private static string DecodeQrFromFileName(string fileName)
    {
        // Expected format: qr_<Data>.png
        string nameWithoutExt = Path.GetFileNameWithoutExtension(fileName);
        int underscoreIndex = nameWithoutExt.IndexOf('_');
        if (underscoreIndex >= 0 && underscoreIndex < nameWithoutExt.Length - 1)
            return nameWithoutExt.Substring(underscoreIndex + 1);
        return string.Empty;
    }
}
