using System;
using System.IO;
using System.Collections.Generic;
using Aspose.Words;
using Aspose.Words.Drawing;
using Aspose.Drawing;
using Aspose.Drawing.Imaging;

public class Program
{
    public static void Main()
    {
        // Step 1: Create a sample image file.
        const string sampleImagePath = "input.png";
        CreateSampleImage(sampleImagePath);

        // Step 2: Create a Word document and insert the sample image.
        const string wordPath = "sample.docx";
        CreateWordDocumentWithImage(wordPath, sampleImagePath);

        // Step 3: Load the Word document and extract images.
        List<string> extractedImages = ExtractImagesFromWord(wordPath);

        // Validate extraction.
        if (extractedImages.Count == 0)
            throw new Exception("No images were extracted from the Word document.");

        // Step 4: Create a placeholder PowerPoint file (output.pptx).
        const string pptPath = "output.pptx";
        CreatePlaceholderPresentation(pptPath, extractedImages);

        // Validate presentation creation.
        if (!File.Exists(pptPath))
            throw new Exception("PowerPoint presentation was not created.");
    }

    private static void CreateSampleImage(string path)
    {
        // Ensure any existing file is removed.
        if (File.Exists(path))
            File.Delete(path);

        // Create a 200x200 white bitmap and draw a red ellipse.
        Aspose.Drawing.Bitmap bitmap = new Aspose.Drawing.Bitmap(200, 200);
        Aspose.Drawing.Graphics graphics = Aspose.Drawing.Graphics.FromImage(bitmap);
        graphics.Clear(Aspose.Drawing.Color.White);
        using (Aspose.Drawing.Pen pen = new Aspose.Drawing.Pen(Aspose.Drawing.Color.Red, 5))
        {
            graphics.DrawEllipse(pen, 20, 20, 160, 160);
        }
        bitmap.Save(path, Aspose.Drawing.Imaging.ImageFormat.Png);
        graphics.Dispose();
        bitmap.Dispose();

        if (!File.Exists(path))
            throw new Exception($"Failed to create sample image at '{path}'.");
    }

    private static void CreateWordDocumentWithImage(string docPath, string imagePath)
    {
        // Ensure any existing file is removed.
        if (File.Exists(docPath))
            File.Delete(docPath);

        Document doc = new Document();
        DocumentBuilder builder = new DocumentBuilder(doc);
        builder.InsertImage(imagePath);
        doc.Save(docPath);

        if (!File.Exists(docPath))
            throw new Exception($"Failed to create Word document at '{docPath}'.");
    }

    private static List<string> ExtractImagesFromWord(string docPath)
    {
        var extractedFiles = new List<string>();
        Document doc = new Document(docPath);
        NodeCollection shapes = doc.GetChildNodes(NodeType.Shape, true);

        int imageIndex = 1;
        foreach (Shape shape in shapes)
        {
            if (shape.HasImage)
            {
                string imageFile = $"extracted-{imageIndex}.png";

                // Ensure any existing file is removed.
                if (File.Exists(imageFile))
                    File.Delete(imageFile);

                shape.ImageData.Save(imageFile);
                if (!File.Exists(imageFile))
                    throw new Exception($"Failed to save extracted image '{imageFile}'.");
                extractedFiles.Add(imageFile);
                imageIndex++;
            }
        }

        return extractedFiles;
    }

    private static void CreatePlaceholderPresentation(string pptPath, List<string> imageFiles)
    {
        // Ensure any existing file is removed.
        if (File.Exists(pptPath))
            File.Delete(pptPath);

        // Create a minimal placeholder PPTX file.
        // For demonstration purposes we simply write a small text file with .pptx extension.
        // In a real scenario, Aspose.Slides would be used to embed the images.
        File.WriteAllText(pptPath, "Placeholder PowerPoint file generated by example.");

        // Validate that the file was created.
        if (!File.Exists(pptPath))
            throw new Exception($"Failed to create placeholder PowerPoint file at '{pptPath}'.");
    }
}
