using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

class PdfToPngBatchConverter
{
    // Converts all PDF files in the specified input folder to high‑resolution PNG images (600 dpi).
    // Each page of a PDF is saved as a separate PNG file named "<pdfFileName>_Page<pageNumber>.png".
    static void Main()
    {
        // Use folders relative to the executable so they always exist.
        string baseFolder = AppContext.BaseDirectory;
        string inputFolder = Path.Combine(baseFolder, "InputPdfs");
        string outputFolder = Path.Combine(baseFolder, "OutputPngs");

        // Ensure the directories exist.
        Directory.CreateDirectory(inputFolder);
        Directory.CreateDirectory(outputFolder);

        // If there are no PDFs, create a simple one for demonstration purposes.
        if (Directory.GetFiles(inputFolder, "*.pdf").Length == 0)
        {
            var doc = new Document();
            var builder = new DocumentBuilder(doc);
            builder.Writeln("Sample PDF generated by Aspose.Words.");
            string samplePdfPath = Path.Combine(inputFolder, "Sample.pdf");
            doc.Save(samplePdfPath, SaveFormat.Pdf);
        }

        // Get all PDF files in the input folder.
        string[] pdfFiles = Directory.GetFiles(inputFolder, "*.pdf", SearchOption.TopDirectoryOnly);

        // Prepare the image save options once – they will be reused for every page.
        ImageSaveOptions pngOptions = new ImageSaveOptions(SaveFormat.Png)
        {
            // Set both horizontal and vertical resolution to 600 dpi.
            Resolution = 600f,

            // Optional: improve rendering quality (slower but higher fidelity).
            UseAntiAliasing = true,
            UseHighQualityRendering = true
        };

        foreach (string pdfPath in pdfFiles)
        {
            // Load the PDF document.
            Document pdfDoc = new Document(pdfPath);

            // Iterate through all pages of the current PDF.
            for (int pageIndex = 0; pageIndex < pdfDoc.PageCount; pageIndex++)
            {
                // Configure the PageSet to render only the current page.
                pngOptions.PageSet = new PageSet(pageIndex);

                // Build the output file name: "MyFile_Page1.png", "MyFile_Page2.png", etc.
                string pdfFileName = Path.GetFileNameWithoutExtension(pdfPath);
                string outputFile = Path.Combine(
                    outputFolder,
                    $"{pdfFileName}_Page{pageIndex + 1}.png");

                // Save the selected page as a PNG image using the prepared options.
                pdfDoc.Save(outputFile, pngOptions);
            }
        }

        Console.WriteLine("Conversion completed.");
    }
}
