using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Create a sample document and save it as PDF (the source for conversion).
        Document sourceDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(sourceDoc);
        builder.Writeln("This is a sample PDF document generated by Aspose.Words.");
        const string pdfPath = "sample.pdf";
        sourceDoc.Save(pdfPath, SaveFormat.Pdf);

        // Load the PDF document.
        Document pdfDoc = new Document(pdfPath);

        // Configure HTML save options to generate an external CSS file.
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions
        {
            CssStyleSheetType = CssStyleSheetType.External // External CSS file.
        };

        // Save the PDF as HTML.
        const string htmlPath = "output.html";
        pdfDoc.Save(htmlPath, htmlOptions);

        // Verify that the external CSS file was created.
        string cssPath = Path.Combine(
            Path.GetDirectoryName(htmlPath) ?? string.Empty,
            Path.GetFileNameWithoutExtension(htmlPath) + ".css");

        if (!File.Exists(cssPath))
            throw new InvalidOperationException("Expected external CSS file was not created.");

        // Optional: Verify that the HTML file references the external CSS.
        string htmlContent = File.ReadAllText(htmlPath);
        if (!htmlContent.Contains($"href=\"{Path.GetFileName(cssPath)}\""))
            throw new InvalidOperationException("HTML does not reference the external CSS file.");

        // Clean up generated files (optional).
        // File.Delete(pdfPath);
        // File.Delete(htmlPath);
        // File.Delete(cssPath);
    }
}
