using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Paths for the temporary PDF and the resulting JPEG image.
        const string pdfPath = "sample.pdf";
        const string jpegPath = "sample.jpg";

        // -----------------------------------------------------------------
        // 1. Create a simple Word document and save it as PDF.
        // -----------------------------------------------------------------
        Document sourceDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(sourceDoc);
        builder.Writeln("This is a sample PDF generated by Aspose.Words.");
        sourceDoc.Save(pdfPath, SaveFormat.Pdf);

        // Verify that the PDF was created.
        if (!File.Exists(pdfPath))
            throw new InvalidOperationException("Failed to create the source PDF file.");

        // -----------------------------------------------------------------
        // 2. Load the PDF document.
        // -----------------------------------------------------------------
        Document pdfDoc = new Document(pdfPath);

        // -----------------------------------------------------------------
        // 3. Convert the PDF to a high‑resolution JPEG image.
        //    Set the JPEG quality to 100 (lowest compression) for maximum quality.
        // -----------------------------------------------------------------
        ImageSaveOptions jpegOptions = new ImageSaveOptions(SaveFormat.Jpeg)
        {
            // 100 = best quality, minimal compression.
            JpegQuality = 100,
            // Render at 300 DPI for a sharper image.
            Resolution = 300
        };

        pdfDoc.Save(jpegPath, jpegOptions);

        // Verify that the JPEG image was created.
        if (!File.Exists(jpegPath))
            throw new InvalidOperationException("The JPEG image was not created.");

        Console.WriteLine($"PDF successfully converted to JPEG: {jpegPath}");
    }
}
