using System;
using System.IO;
using System.Text;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Prepare output directory.
        string outputDir = Path.Combine(Directory.GetCurrentDirectory(), "Output");
        Directory.CreateDirectory(outputDir);

        // 1. Create a simple Word document and save it as PDF.
        string pdfPath = Path.Combine(outputDir, "sample.pdf");
        Document doc = new Document();
        DocumentBuilder builder = new DocumentBuilder(doc);
        builder.Writeln("Hello, this is a sample PDF generated by Aspose.Words.");
        doc.Save(pdfPath, SaveFormat.Pdf);

        // Verify PDF creation.
        if (!File.Exists(pdfPath) || new FileInfo(pdfPath).Length == 0)
            throw new InvalidOperationException("Failed to create PDF file.");

        // 2. Load the PDF and convert it to MHTML.
        string mhtmlPath = Path.Combine(outputDir, "sample.mhtml");
        Document pdfDoc = new Document(pdfPath);
        HtmlSaveOptions mhtmlOptions = new HtmlSaveOptions(SaveFormat.Mhtml)
        {
            ExportCidUrlsForMhtmlResources = true
        };
        pdfDoc.Save(mhtmlPath, mhtmlOptions);

        // Verify MHTML creation.
        if (!File.Exists(mhtmlPath) || new FileInfo(mhtmlPath).Length == 0)
            throw new InvalidOperationException("Failed to create MHTML file.");

        // 3. Build a simple MIME email with the MHTML attached using a custom MIME type.
        // Since Aspose.Email is not available, construct the .eml file manually.
        string emlPath = Path.Combine(outputDir, "email.eml");
        string boundary = "----=_Boundary_" + Guid.NewGuid().ToString("N");

        // Read the MHTML file and encode it in Base64.
        byte[] mhtmlBytes = File.ReadAllBytes(mhtmlPath);
        string mhtmlBase64 = Convert.ToBase64String(mhtmlBytes);

        // Build the MIME content.
        StringBuilder mimeBuilder = new StringBuilder();
        mimeBuilder.AppendLine("From: sender@example.com");
        mimeBuilder.AppendLine("To: recipient@example.com");
        mimeBuilder.AppendLine("Subject: Sample MHTML Attachment");
        mimeBuilder.AppendLine("MIME-Version: 1.0");
        mimeBuilder.AppendLine($"Content-Type: multipart/mixed; boundary=\"{boundary}\"");
        mimeBuilder.AppendLine();
        mimeBuilder.AppendLine($"--{boundary}");
        mimeBuilder.AppendLine("Content-Type: text/plain; charset=\"utf-8\"");
        mimeBuilder.AppendLine("Content-Transfer-Encoding: 7bit");
        mimeBuilder.AppendLine();
        mimeBuilder.AppendLine("Please find the attached MHTML document.");
        mimeBuilder.AppendLine();
        mimeBuilder.AppendLine($"--{boundary}");
        mimeBuilder.AppendLine("Content-Type: application/custom-mhtml");
        mimeBuilder.AppendLine("Content-Transfer-Encoding: base64");
        mimeBuilder.AppendLine("Content-Disposition: attachment; filename=\"sample.mhtml\"");
        mimeBuilder.AppendLine();
        // Insert the Base64 content, split into 76‑character lines as per RFC 2045.
        for (int i = 0; i < mhtmlBase64.Length; i += 76)
        {
            int length = Math.Min(76, mhtmlBase64.Length - i);
            mimeBuilder.AppendLine(mhtmlBase64.Substring(i, length));
        }
        mimeBuilder.AppendLine();
        mimeBuilder.AppendLine($"--{boundary}--");
        mimeBuilder.AppendLine();

        // Write the .eml file.
        File.WriteAllText(emlPath, mimeBuilder.ToString(), Encoding.UTF8);

        // Verify email file creation.
        if (!File.Exists(emlPath) || new FileInfo(emlPath).Length == 0)
            throw new InvalidOperationException("Failed to save the email message.");
    }
}
