using System;
using System.IO;
using Aspose.Words;

namespace PdfToDocxConversion
{
    class Program
    {
        static void Main(string[] args)
        {
            // Determine working directory.
            string workDir = Directory.GetCurrentDirectory();

            // Paths for the temporary PDF and the resulting DOCX.
            string pdfPath = Path.Combine(workDir, "sample.pdf");
            string docxPath = Path.Combine(workDir, "sample.docx");

            // If the PDF does not exist, create a simple one first.
            if (!File.Exists(pdfPath))
            {
                // Create a basic Word document.
                Document tempDoc = new Document();
                DocumentBuilder builder = new DocumentBuilder(tempDoc);
                builder.Writeln("This is a sample PDF generated by Aspose.Words.");
                builder.Writeln("It will be converted to DOCX while preserving formatting and hyperlinks.");

                // Save it as PDF.
                tempDoc.Save(pdfPath, SaveFormat.Pdf);
            }

            // Load the PDF document. The Document constructor automatically detects the format.
            Document pdfDocument = new Document(pdfPath);

            // Save the loaded document as DOCX. The Save method determines the format from the file extension.
            pdfDocument.Save(docxPath, SaveFormat.Docx);

            Console.WriteLine($"Conversion completed successfully.");
            Console.WriteLine($"PDF source: {pdfPath}");
            Console.WriteLine($"DOCX output: {docxPath}");
        }
    }
}
