using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Define output directory and ensure it exists.
        string outputDir = Path.Combine(Directory.GetCurrentDirectory(), "Output");
        Directory.CreateDirectory(outputDir);

        // Create a sample PDF document.
        Document sampleDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(sampleDoc);
        builder.Writeln("This is a sample PDF generated by Aspose.Words.");
        string pdfPath = Path.Combine(outputDir, "sample.pdf");
        sampleDoc.Save(pdfPath, SaveFormat.Pdf);

        // Load the PDF document.
        Document pdfDoc = new Document(pdfPath);

        // Convert the PDF to JPEG.
        string jpegPath = Path.Combine(outputDir, "sample.jpg");
        pdfDoc.Save(jpegPath, SaveFormat.Jpeg);

        // Convert the PDF to PNG.
        string pngPath = Path.Combine(outputDir, "sample.png");
        pdfDoc.Save(pngPath, SaveFormat.Png);

        // Validate that the output files were created.
        if (!File.Exists(jpegPath))
            throw new InvalidOperationException("JPEG image was not created.");

        if (!File.Exists(pngPath))
            throw new InvalidOperationException("PNG image was not created.");
    }
}
