using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Define output directories.
        string baseDir = Path.Combine(Directory.GetCurrentDirectory(), "Output");
        string imagesDir = Path.Combine(baseDir, "Images");
        string cssFilePath = Path.Combine(baseDir, "styles.css");
        string pdfPath = Path.Combine(baseDir, "sample.pdf");
        string htmlPath = Path.Combine(baseDir, "sample.html");

        // Ensure directories exist.
        Directory.CreateDirectory(baseDir);
        Directory.CreateDirectory(imagesDir);

        // -----------------------------------------------------------------
        // 1. Create a sample PDF document.
        // -----------------------------------------------------------------
        Document sourceDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(sourceDoc);
        builder.Writeln("This is a sample PDF generated by Aspose.Words.");
        builder.Writeln("It will be converted to HTML with external CSS and images.");
        sourceDoc.Save(pdfPath, SaveFormat.Pdf);

        // Verify PDF creation.
        if (!File.Exists(pdfPath))
            throw new InvalidOperationException("PDF file was not created.");

        // -----------------------------------------------------------------
        // 2. Load the PDF and convert it to HTML.
        // -----------------------------------------------------------------
        Document pdfDoc = new Document(pdfPath);

        HtmlSaveOptions htmlOptions = new HtmlSaveOptions
        {
            // Export CSS to an external file.
            CssStyleSheetType = CssStyleSheetType.External,
            CssStyleSheetFileName = cssFilePath,

            // Export images to a separate folder.
            ImagesFolder = imagesDir,

            // Keep image URIs relative to the ImagesFolder.
            ImagesFolderAlias = "Images"
        };

        pdfDoc.Save(htmlPath, htmlOptions);

        // -----------------------------------------------------------------
        // 3. Validate the conversion results.
        // -----------------------------------------------------------------
        if (!File.Exists(htmlPath))
            throw new InvalidOperationException("HTML file was not created.");

        if (!File.Exists(cssFilePath))
            throw new InvalidOperationException("CSS file was not created.");

        // At least one image file should exist (Aspose may generate images for vector graphics, etc.).
        string[] imageFiles = Directory.GetFiles(imagesDir);
        if (imageFiles.Length == 0)
            throw new InvalidOperationException("No images were exported to the Images folder.");

        // Output paths for confirmation (optional, not required by the task).
        Console.WriteLine("Conversion completed successfully.");
        Console.WriteLine($"HTML file: {htmlPath}");
        Console.WriteLine($"CSS file: {cssFilePath}");
        Console.WriteLine($"Images folder: {imagesDir}");
    }
}
