using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Create a simple Word document and save it as PDF (the source PDF).
        Document sourceDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(sourceDoc);
        builder.Writeln("Sample PDF content generated by Aspose.Words.");
        const string pdfPath = "sample.pdf";
        sourceDoc.Save(pdfPath, SaveFormat.Pdf);

        // Load the PDF document.
        Document pdfDoc = new Document(pdfPath);

        // Convert the PDF to JPEG.
        const string jpegPath = "sample.jpg";
        ImageSaveOptions jpegOptions = new ImageSaveOptions(SaveFormat.Jpeg);
        pdfDoc.Save(jpegPath, jpegOptions);

        // Convert the PDF to PNG.
        const string pngPath = "sample.png";
        ImageSaveOptions pngOptions = new ImageSaveOptions(SaveFormat.Png);
        pdfDoc.Save(pngPath, pngOptions);

        // Verify that the output files were created.
        if (!File.Exists(jpegPath))
            throw new InvalidOperationException($"Expected JPEG file was not created: {jpegPath}");
        if (!File.Exists(pngPath))
            throw new InvalidOperationException($"Expected PNG file was not created: {pngPath}");

        // Optionally, clean up the intermediate PDF if not needed.
        // File.Delete(pdfPath);
    }
}
