using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Prepare output folder.
        const string outputFolder = "Output";
        Directory.CreateDirectory(outputFolder);

        // -----------------------------------------------------------------
        // 1. Create a sample PDF document.
        // -----------------------------------------------------------------
        Document sourceDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(sourceDoc);
        builder.Writeln("This is a sample PDF document generated by Aspose.Words.");
        builder.Writeln("It contains multiple pages for conversion testing.");
        // Insert a page break to create a second page.
        builder.InsertBreak(BreakType.PageBreak);
        builder.Writeln("Second page content.");

        const string pdfPath = "sample.pdf";
        sourceDoc.Save(pdfPath, SaveFormat.Pdf);

        if (!File.Exists(pdfPath))
            throw new InvalidOperationException("Failed to create the source PDF file.");

        // -----------------------------------------------------------------
        // 2. Load the PDF document.
        // -----------------------------------------------------------------
        Document pdfDoc = new Document(pdfPath);

        // -----------------------------------------------------------------
        // 3. Convert each PDF page to a high‑quality JPEG image.
        // -----------------------------------------------------------------
        for (int pageIndex = 0; pageIndex < pdfDoc.PageCount; pageIndex++)
        {
            // Configure image save options for JPEG with maximum quality.
            ImageSaveOptions jpegOptions = new ImageSaveOptions(SaveFormat.Jpeg)
            {
                JpegQuality = 100,                     // Highest quality (no compression artifacts).
                PageSet = new PageSet(pageIndex)       // Render only the current page.
            };

            string jpegPath = Path.Combine(outputFolder, $"Page_{pageIndex + 1}.jpg");
            pdfDoc.Save(jpegPath, jpegOptions);

            if (!File.Exists(jpegPath))
                throw new InvalidOperationException($"Failed to create JPEG image for page {pageIndex + 1}.");
        }

        // -----------------------------------------------------------------
        // 4. Clean up temporary files (optional).
        // -----------------------------------------------------------------
        // File.Delete(pdfPath); // Uncomment if you want to remove the intermediate PDF.

        Console.WriteLine("PDF conversion to high‑quality JPEG images completed successfully.");
    }
}
