using System;
using System.IO;
using System.Net.Mail;
using System.Net.Mime;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Step 1: Create a sample PDF document.
        Document sourceDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(sourceDoc);
        builder.Writeln("This is a sample PDF generated by Aspose.Words.");
        const string pdfPath = "sample.pdf";
        sourceDoc.Save(pdfPath, SaveFormat.Pdf);

        if (!File.Exists(pdfPath))
            throw new InvalidOperationException("PDF file was not created.");

        // Step 2: Load the PDF and convert it to MHTML.
        Document pdfDoc = new Document(pdfPath);
        const string mhtmlPath = "sample.mht";
        HtmlSaveOptions mhtmlOptions = new HtmlSaveOptions(SaveFormat.Mhtml);
        pdfDoc.Save(mhtmlPath, mhtmlOptions);

        if (!File.Exists(mhtmlPath))
            throw new InvalidOperationException("MHTML file was not created.");

        // Step 3: Prepare the MHTML content for email attachment.
        byte[] mhtmlBytes = File.ReadAllBytes(mhtmlPath);
        using MemoryStream mhtmlStream = new MemoryStream(mhtmlBytes);
        mhtmlStream.Position = 0; // Ensure the stream is at the beginning.

        // Step 4: Create an email message with a custom MIME type for the attachment.
        MailMessage message = new MailMessage(
            "sender@example.com",
            "recipient@example.com",
            "Converted PDF to MHTML",
            "Please find the converted MHTML document attached.");

        ContentType customContentType = new ContentType("application/mhtml");
        Attachment attachment = new Attachment(mhtmlStream, "sample.mht", customContentType.MediaType);
        message.Attachments.Add(attachment);

        // Step 5: Send the email using a local pickup directory.
        // SmtpClient requires an absolute path for the pickup directory.
        string pickupDir = Path.GetFullPath("EmailPickup");
        if (!Directory.Exists(pickupDir))
            Directory.CreateDirectory(pickupDir);

        using (SmtpClient client = new SmtpClient
        {
            DeliveryMethod = SmtpDeliveryMethod.SpecifiedPickupDirectory,
            PickupDirectoryLocation = pickupDir
        })
        {
            client.Send(message);
        }

        // Verify that the email file was written to the pickup directory.
        string[] emlFiles = Directory.GetFiles(pickupDir, "*.eml");
        if (emlFiles.Length == 0)
            throw new InvalidOperationException("Email was not saved to the pickup directory.");

        // Cleanup temporary files.
        File.Delete(pdfPath);
        File.Delete(mhtmlPath);
    }
}
