using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

namespace AsposeWordsHtmlConversion
{
    // Custom callback to control how the CSS file is written during HTML export.
    public class CustomCssSavingCallback : ICssSavingCallback
    {
        private readonly string _cssFilePath;

        public CustomCssSavingCallback(string cssFilePath)
        {
            _cssFilePath = cssFilePath;
        }

        public void CssSaving(CssSavingArgs args)
        {
            // Create (or overwrite) the CSS file.
            args.CssStream = new FileStream(_cssFilePath, FileMode.Create, FileAccess.Write);
            args.IsExportNeeded = true;          // Ensure the CSS is exported.
            args.KeepCssStreamOpen = false;      // Let Aspose.Words close the stream after saving.

            // Write custom CSS rules.
            using (var writer = new StreamWriter(args.CssStream))
            {
                writer.WriteLine("/* Custom CSS generated by Aspose.Words */");
                writer.WriteLine(".custom-paragraph {");
                writer.WriteLine("    margin-top: 10pt;");
                writer.WriteLine("    margin-bottom: 10pt;");
                writer.WriteLine("    line-height: 1.5;");
                writer.WriteLine("}");
                writer.WriteLine(".custom-heading {");
                writer.WriteLine("    color: #2E86C1;");
                writer.WriteLine("    font-weight: bold;");
                writer.WriteLine("}");
            }
        }
    }

    public static class DocxToHtmlConverter
    {
        /// <summary>
        /// Converts a DOCX document to an HTML file that references an external CSS stylesheet.
        /// </summary>
        /// <param name="docxPath">Path to the source DOCX file.</param>
        /// <param name="htmlPath">Path where the resulting HTML file will be saved.</param>
        /// <param name="cssPath">Path where the external CSS file will be saved.</param>
        public static void Convert(string docxPath, string htmlPath, string cssPath)
        {
            // Load the DOCX document.
            Document doc = new Document(docxPath);

            // Configure HTML save options to use an external stylesheet.
            HtmlSaveOptions saveOptions = new HtmlSaveOptions
            {
                CssStyleSheetType = CssStyleSheetType.External, // Export CSS to a separate file.
                CssStyleSheetFileName = cssPath,                // Name of the external CSS file.
                CssSavingCallback = new CustomCssSavingCallback(cssPath), // Use custom CSS content.
                CssClassNamePrefix = "custom",                 // Optional prefix for generated class names.
                ExportGeneratorName = false                    // Do not embed Aspose.Words generator comment.
            };

            // Save the document as HTML using the configured options.
            doc.Save(htmlPath, saveOptions);
        }
    }

    // Example usage.
    class Program
    {
        static void Main()
        {
            string inputDocx = @"C:\Docs\Sample.docx";
            string outputHtml = @"C:\Docs\Sample.html";
            string outputCss = @"C:\Docs\Sample.css";

            DocxToHtmlConverter.Convert(inputDocx, outputHtml, outputCss);

            Console.WriteLine("Conversion completed.");
        }
    }
}
