using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;
using Aspose.Drawing;
using Aspose.Drawing.Imaging;

public class Program
{
    public static void Main()
    {
        // Paths for the sample files
        const string pdfPath = "sample.pdf";
        const string htmlPath = "output.html";

        // Clean any previous output
        if (File.Exists(pdfPath)) File.Delete(pdfPath);
        if (File.Exists(htmlPath)) File.Delete(htmlPath);

        // -----------------------------------------------------------------
        // 1. Create a simple Word document, insert a tiny image, and save as PDF
        // -----------------------------------------------------------------
        Document doc = new Document();
        DocumentBuilder builder = new DocumentBuilder(doc);
        builder.Writeln("This is a sample PDF generated by Aspose.Words.");

        // Insert a 1x1 red PNG created with Aspose.Drawing
        builder.InsertImage(CreatePlaceholderPng());

        doc.Save(pdfPath, SaveFormat.Pdf);

        if (!File.Exists(pdfPath))
            throw new InvalidOperationException("Failed to create the sample PDF.");

        // -----------------------------------------------------------------
        // 2. Load the PDF and convert it to HTML
        // -----------------------------------------------------------------
        Document pdfDoc = new Document(pdfPath);

        // Configure HTML save options:
        // - Export images as external files (not Base64)
        // - Keep default behavior for font embedding (fonts are embedded as Base64 by default)
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions
        {
            ExportImagesAsBase64 = false
        };

        pdfDoc.Save(htmlPath, htmlOptions);

        // -----------------------------------------------------------------
        // 3. Validate the conversion result
        // -----------------------------------------------------------------
        if (!File.Exists(htmlPath))
            throw new InvalidOperationException("HTML file was not created.");

        // The HTML may reference external image files placed in a folder
        // named after the HTML file (e.g., output_files). Verify that such a folder exists.
        string expectedImageFolder = Path.GetFileNameWithoutExtension(htmlPath) + "_files";
        if (Directory.Exists(expectedImageFolder))
        {
            string[] imageFiles = Directory.GetFiles(expectedImageFolder);
            if (imageFiles.Length == 0)
                throw new InvalidOperationException("No images were exported to the image folder.");
        }

        Console.WriteLine("PDF successfully converted to HTML with embedded fonts and external images.");
    }

    // Generates a simple 1x1 red PNG image in memory using Aspose.Drawing.
    private static byte[] CreatePlaceholderPng()
    {
        using (Bitmap bitmap = new Bitmap(1, 1))
        {
            using (Graphics graphics = Graphics.FromImage(bitmap))
            {
                graphics.Clear(Aspose.Drawing.Color.Red);
            }

            using (MemoryStream ms = new MemoryStream())
            {
                bitmap.Save(ms, ImageFormat.Png);
                return ms.ToArray();
            }
        }
    }
}
