using System;
using System.IO;
using System.Text;
using Aspose.Words;

public class Program
{
    public static void Main(string[] args)
    {
        // Step 1: Create a sample PDF document using Aspose.Words.
        Document sampleDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(sampleDoc);
        builder.Writeln("Sample PDF content generated by Aspose.Words.");
        string pdfPath = "sample.pdf";
        sampleDoc.Save(pdfPath, SaveFormat.Pdf);

        if (!File.Exists(pdfPath))
            throw new InvalidOperationException("The sample PDF file was not created.");

        // Step 2: Load the PDF document.
        Document pdfDocument = new Document(pdfPath);

        // Step 3: Convert the PDF to MHTML and store it in a memory stream.
        using MemoryStream mhtmlStream = new MemoryStream();
        pdfDocument.Save(mhtmlStream, SaveFormat.Mhtml);

        if (mhtmlStream.Length == 0)
            throw new InvalidOperationException("MHTML conversion produced an empty stream.");

        // Reset the stream position before reading its content.
        mhtmlStream.Position = 0;

        // Step 4: Build a simple MIME email with the MHTML attachment and a custom MIME type.
        string from = "sender@example.com";
        string to = "recipient@example.com";
        string subject = "Converted PDF to MHTML";
        string bodyText = "Please find the converted MHTML file attached.";

        // Read the MHTML bytes and encode them as Base64.
        byte[] mhtmlBytes = mhtmlStream.ToArray();
        string mhtmlBase64 = Convert.ToBase64String(mhtmlBytes, Base64FormattingOptions.InsertLineBreaks);

        // Create a unique boundary for the multipart message.
        string boundary = "----=_AsposeBoundary_" + Guid.NewGuid().ToString("N");

        StringBuilder emlBuilder = new StringBuilder();

        // Email headers.
        emlBuilder.AppendLine($"From: {from}");
        emlBuilder.AppendLine($"To: {to}");
        emlBuilder.AppendLine($"Subject: {subject}");
        emlBuilder.AppendLine("MIME-Version: 1.0");
        emlBuilder.AppendLine($"Content-Type: multipart/mixed; boundary=\"{boundary}\"");
        emlBuilder.AppendLine();

        // Email body part.
        emlBuilder.AppendLine($"--{boundary}");
        emlBuilder.AppendLine("Content-Type: text/plain; charset=\"utf-8\"");
        emlBuilder.AppendLine("Content-Transfer-Encoding: 7bit");
        emlBuilder.AppendLine();
        emlBuilder.AppendLine(bodyText);
        emlBuilder.AppendLine();

        // Attachment part with custom MIME type.
        emlBuilder.AppendLine($"--{boundary}");
        emlBuilder.AppendLine("Content-Type: application/custom-mhtml; name=\"converted.mht\"");
        emlBuilder.AppendLine("Content-Transfer-Encoding: base64");
        emlBuilder.AppendLine("Content-Disposition: attachment; filename=\"converted.mht\"");
        emlBuilder.AppendLine();
        emlBuilder.AppendLine(mhtmlBase64);
        emlBuilder.AppendLine();

        // End of multipart message.
        emlBuilder.AppendLine($"--{boundary}--");
        emlBuilder.AppendLine();

        // Step 5: Save the MIME message to an .eml file.
        string emlPath = "email.eml";
        File.WriteAllText(emlPath, emlBuilder.ToString(), Encoding.UTF8);

        if (!File.Exists(emlPath))
            throw new InvalidOperationException("The email .eml file was not created.");

        // Optional cleanup (commented out).
        // File.Delete(pdfPath);
        // File.Delete(emlPath);
    }
}
