using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Create a sample PDF document.
        Document sourceDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(sourceDoc);
        builder.Writeln("This is a sample PDF generated by Aspose.Words.");
        const string pdfPath = "sample.pdf";
        sourceDoc.Save(pdfPath, SaveFormat.Pdf);

        // Load the PDF document.
        Document pdfDoc = new Document(pdfPath);

        // Convert the PDF to JPEG.
        const string jpegPath = "sample.jpg";
        pdfDoc.Save(jpegPath, SaveFormat.Jpeg);

        // Convert the PDF to PNG.
        const string pngPath = "sample.png";
        pdfDoc.Save(pngPath, SaveFormat.Png);

        // Verify that the output files were created.
        if (!File.Exists(pdfPath))
            throw new InvalidOperationException("PDF file was not created.");
        if (!File.Exists(jpegPath))
            throw new InvalidOperationException("JPEG image was not created.");
        if (!File.Exists(pngPath))
            throw new InvalidOperationException("PNG image was not created.");
    }
}
