using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Define a working directory for all generated files.
        string workDir = Path.Combine(Directory.GetCurrentDirectory(), "Output");
        Directory.CreateDirectory(workDir);

        // -----------------------------------------------------------------
        // Step 1: Create a sample PDF document.
        // -----------------------------------------------------------------
        Document sourceDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(sourceDoc);
        builder.Writeln("This is a sample PDF document generated by Aspose.Words.");
        // Save the document as PDF.
        string pdfPath = Path.Combine(workDir, "sample.pdf");
        sourceDoc.Save(pdfPath, SaveFormat.Pdf);

        // Verify that the PDF was created.
        if (!File.Exists(pdfPath))
            throw new InvalidOperationException("Failed to create the sample PDF file.");

        // -----------------------------------------------------------------
        // Step 2: Load the PDF and convert it to HTML.
        // -----------------------------------------------------------------
        Document pdfDoc = new Document(pdfPath);

        // Prepare HTML save options:
        // - Embed fonts as Base64.
        // - Keep images as external files.
        // - Store external images in a dedicated folder.
        string imagesFolder = Path.Combine(workDir, "Images");
        Directory.CreateDirectory(imagesFolder);

        HtmlSaveOptions htmlOptions = new HtmlSaveOptions
        {
            ExportFontsAsBase64 = true,
            ExportImagesAsBase64 = false,
            ImagesFolder = imagesFolder,
            PrettyFormat = true
        };

        // Save the PDF as HTML using the configured options.
        string htmlPath = Path.Combine(workDir, "output.html");
        pdfDoc.Save(htmlPath, htmlOptions);

        // -----------------------------------------------------------------
        // Step 3: Validation.
        // -----------------------------------------------------------------
        if (!File.Exists(htmlPath))
            throw new InvalidOperationException("HTML conversion failed; output file not found.");

        // Ensure that at least one image file was created in the images folder.
        string[] imageFiles = Directory.GetFiles(imagesFolder);
        if (imageFiles.Length == 0)
            throw new InvalidOperationException("No external image files were generated during conversion.");

        // Optionally, output the locations of the generated files.
        Console.WriteLine("Conversion completed successfully.");
        Console.WriteLine($"PDF file: {pdfPath}");
        Console.WriteLine($"HTML file: {htmlPath}");
        Console.WriteLine($"Images folder: {imagesFolder}");
    }
}
