using System;
using System.IO;
using System.Net;
using System.Net.Mail;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Create a simple Word document in memory.
        Document doc = new Document();
        DocumentBuilder builder = new DocumentBuilder(doc);
        builder.Writeln("Hello, this is a sample MHTML content generated by Aspose.Words.");

        // Save the document as MHTML (Web archive) to a local file.
        string mhtmlPath = "sample.mht";
        doc.Save(mhtmlPath, SaveFormat.Mhtml);

        // Verify that the MHTML file was created.
        if (!File.Exists(mhtmlPath))
            throw new InvalidOperationException("MHTML file was not created.");

        // Prepare an email message.
        MailMessage mail = new MailMessage();
        mail.From = new MailAddress("sender@example.com");
        mail.To.Add("recipient@example.com");
        mail.Subject = "Test email with MHTML attachment";
        mail.Body = "Please see the attached MHTML file.";
        mail.Attachments.Add(new Attachment(mhtmlPath));

        // Configure the SMTP client. Adjust host/port as needed for a real server.
        SmtpClient smtp = new SmtpClient("localhost", 25)
        {
            // If a real SMTP server requires credentials, set them here.
            // Credentials = new NetworkCredential("username", "password"),
            EnableSsl = false,
            DeliveryMethod = SmtpDeliveryMethod.Network,
            Timeout = 10000
        };

        try
        {
            // Attempt to send the email.
            smtp.Send(mail);
            Console.WriteLine("Email sent successfully.");
        }
        catch (Exception ex)
        {
            // In environments without an SMTP server, sending will fail.
            // The exception is caught to allow the program to finish gracefully.
            Console.WriteLine("SMTP send failed: " + ex.Message);
        }
        finally
        {
            // Clean up resources.
            mail.Dispose();
            smtp.Dispose();

            // Optionally delete the temporary MHTML file.
            if (File.Exists(mhtmlPath))
                File.Delete(mhtmlPath);
        }
    }
}
