using System;
using System.IO;
using System.Net;
using System.Net.Mail;
using Aspose.Words;
using Aspose.Words.Saving;

namespace AsposeWordsEmailExample
{
    class Program
    {
        static void Main()
        {
            // 1. Create a simple Word document.
            Document doc = new Document();
            DocumentBuilder builder = new DocumentBuilder(doc);
            builder.Writeln("Hello, this is a test document generated by Aspose.Words.");
            builder.Writeln("It will be saved as MHTML and sent as an email attachment.");

            // 2. Save the document as an MHTML file.
            string mhtmlPath = Path.Combine(Path.GetTempPath(), "TestDocument.mht");
            doc.Save(mhtmlPath, SaveFormat.Mhtml);

            // 3. Prepare the email message with the MHTML attachment.
            using (var message = new MailMessage())
            {
                message.From = new MailAddress("sender@example.com");
                message.To.Add("recipient@example.com");
                message.Subject = "Test Email with MHTML Attachment";
                message.Body = "Please find the attached MHTML document.";

                using (var attachment = new Attachment(mhtmlPath, "application/octet-stream"))
                {
                    attachment.Name = "TestDocument.mht";
                    message.Attachments.Add(attachment);

                    // 4. Configure the SMTP client to use a local pickup directory (no real server needed).
                    using (var smtpClient = new SmtpClient())
                    {
                        string pickupDir = Path.Combine(Path.GetTempPath(), "maildrop");
                        Directory.CreateDirectory(pickupDir);

                        smtpClient.DeliveryMethod = SmtpDeliveryMethod.SpecifiedPickupDirectory;
                        smtpClient.PickupDirectoryLocation = pickupDir;

                        try
                        {
                            smtpClient.Send(message);
                            Console.WriteLine("Email saved to pickup directory successfully.");
                        }
                        catch (SmtpException ex)
                        {
                            Console.WriteLine($"SMTP error: {ex.StatusCode} - {ex.Message}");
                        }
                    }
                }
            }

            // 5. Clean up the temporary MHTML file.
            if (File.Exists(mhtmlPath))
            {
                File.Delete(mhtmlPath);
            }
        }
    }
}
