using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Loading;
using Aspose.Words.Saving;

class HtmlToPdfConverter
{
    static void Main()
    {
        // Create a temporary folder for input and output files.
        string tempFolder = Path.Combine(Path.GetTempPath(), "HtmlToPdfDemo");
        Directory.CreateDirectory(tempFolder);

        // Input HTML file (created on the fly).
        string htmlPath = Path.Combine(tempFolder, "sample.html");
        string htmlContent = @"
<!DOCTYPE html>
<html>
<head>
    <title>Sample</title>
    <script>
        // This script will be ignored during conversion.
        document.write('This text is generated by JavaScript.');
    </script>
</head>
<body>
    <h1>Hello, World!</h1>
    <noscript>This content is shown when scripts are disabled.</noscript>
</body>
</html>";
        File.WriteAllText(htmlPath, htmlContent);

        // Desired output PDF file.
        string pdfPath = Path.Combine(tempFolder, "sample.pdf");

        // Load options: ignore <noscript> elements so script‑related content is not rendered.
        HtmlLoadOptions loadOptions = new HtmlLoadOptions
        {
            IgnoreNoscriptElements = true
        };

        // Load the HTML document with the specified options.
        Document doc = new Document(htmlPath, loadOptions);

        // PDF save options (default configuration is sufficient for static rendering).
        PdfSaveOptions saveOptions = new PdfSaveOptions();

        // Save the loaded document as PDF.
        doc.Save(pdfPath, saveOptions);

        Console.WriteLine($"PDF successfully created at: {pdfPath}");
    }
}
