using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Loading;

public class Program
{
    public static void Main()
    {
        // Prepare a sample HTML file that contains a script element.
        const string htmlFile = "input.html";
        const string htmlContent = @"
<!DOCTYPE html>
<html>
<head>
    <title>Sample</title>
    <script type=""text/javascript"">
        // This script will be ignored by Aspose.Words during conversion.
        document.write('This text is generated by JavaScript.');
    </script>
</head>
<body>
    <h1>Hello World</h1>
    <p>This paragraph is static content.</p>
</body>
</html>";
        File.WriteAllText(htmlFile, htmlContent);

        // Load the HTML document. Aspose.Words does not execute JavaScript,
        // so the script element is ignored automatically.
        HtmlLoadOptions loadOptions = new HtmlLoadOptions();
        Document doc = new Document(htmlFile, loadOptions);

        // Convert the loaded document to PDF.
        const string pdfFile = "output.pdf";
        doc.Save(pdfFile, SaveFormat.Pdf);

        // Verify that the PDF was created.
        if (!File.Exists(pdfFile) || new FileInfo(pdfFile).Length == 0)
        {
            throw new InvalidOperationException("PDF conversion failed: output file was not created.");
        }

        Console.WriteLine($"HTML file '{htmlFile}' successfully converted to PDF '{pdfFile}'.");
    }
}
