using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Loading;

public class Program
{
    public static void Main()
    {
        // Paths for the temporary PDF and the final DOCX output.
        const string pdfPath = "sample.pdf";
        const string docxPath = "output.docx";

        // -----------------------------------------------------------------
        // 1. Create a simple PDF file to work with.
        // -----------------------------------------------------------------
        Document source = new Document();
        DocumentBuilder builder = new DocumentBuilder(source);
        builder.Writeln("Sample PDF content generated by Aspose.Words.");
        source.Save(pdfPath, SaveFormat.Pdf);

        // -----------------------------------------------------------------
        // 2. Load the PDF using PdfLoadOptions.
        //    No password is supplied, effectively ignoring password protection.
        // -----------------------------------------------------------------
        PdfLoadOptions loadOptions = new PdfLoadOptions();
        // If the PDF were password‑protected, setting loadOptions.Password to null
        // (the default) would cause an IncorrectPasswordException.
        // For this example the PDF is not protected, so loading succeeds.
        Document pdfDoc = new Document(pdfPath, loadOptions);

        // -----------------------------------------------------------------
        // 3. Save the loaded document as DOCX.
        // -----------------------------------------------------------------
        pdfDoc.Save(docxPath, SaveFormat.Docx);

        // -----------------------------------------------------------------
        // 4. Validate that the DOCX file was created.
        // -----------------------------------------------------------------
        if (!File.Exists(docxPath))
            throw new InvalidOperationException("The DOCX output file was not created.");

        // The example finishes without waiting for user input.
    }
}
