using System;
using System.IO;
using Aspose.Words;

public class Program
{
    public static void Main()
    {
        // Define file names for the intermediate PDF and the final DOCX.
        const string pdfPath = "sample.pdf";
        const string docxPath = "converted.docx";

        // -----------------------------------------------------------------
        // Step 1: Create a simple Word document and save it as PDF.
        // This provides a local PDF file for the conversion example.
        // -----------------------------------------------------------------
        Document sourceDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(sourceDoc);
        builder.Writeln("This is a sample PDF generated by Aspose.Words.");
        sourceDoc.Save(pdfPath, SaveFormat.Pdf);

        // Verify that the PDF was created.
        if (!File.Exists(pdfPath))
            throw new InvalidOperationException("Failed to create the source PDF file.");

        // -----------------------------------------------------------------
        // Step 2: Load the PDF file.
        // -----------------------------------------------------------------
        Document pdfDoc = new Document(pdfPath);

        // -----------------------------------------------------------------
        // Step 3: Convert the loaded PDF to DOCX format.
        // -----------------------------------------------------------------
        pdfDoc.Save(docxPath, SaveFormat.Docx);

        // Verify that the DOCX was created.
        if (!File.Exists(docxPath))
            throw new InvalidOperationException("The DOCX conversion output was not created.");

        // Optional: Inform that the conversion succeeded (no interactive input required).
        Console.WriteLine("PDF successfully converted to DOCX.");
    }
}
