using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main(string[] args)
    {
        // Define file names.
        const string pdfPath = "sample.pdf";
        const string pngPath = "sample.png";

        // -----------------------------------------------------------------
        // Step 1: Create a sample PDF document.
        // -----------------------------------------------------------------
        Document doc = new Document();
        DocumentBuilder builder = new DocumentBuilder(doc);
        builder.Writeln("This is a sample PDF document generated by Aspose.Words.");
        builder.Writeln("It will be converted to a high‑resolution PNG image.");
        // Save the document as PDF.
        doc.Save(pdfPath, SaveFormat.Pdf);

        // Verify that the PDF was created.
        if (!File.Exists(pdfPath))
            throw new InvalidOperationException("The PDF file was not created.");

        // -----------------------------------------------------------------
        // Step 2: Load the PDF and convert it to a high‑resolution PNG.
        // -----------------------------------------------------------------
        Document pdfDoc = new Document(pdfPath);

        // Configure image save options for high resolution (e.g., 300 DPI).
        ImageSaveOptions pngOptions = new ImageSaveOptions(SaveFormat.Png)
        {
            Resolution = 300 // Dots per inch.
        };

        // Save the first page of the PDF as a PNG image.
        // When saving to an image format, Aspose.Words renders each page separately.
        // Since the sample PDF has only one page, a single PNG file will be produced.
        pdfDoc.Save(pngPath, pngOptions);

        // Verify that the PNG was created.
        if (!File.Exists(pngPath))
            throw new InvalidOperationException("The PNG image was not created.");

        // -----------------------------------------------------------------
        // Cleanup (optional): delete temporary files if desired.
        // -----------------------------------------------------------------
        // File.Delete(pdfPath);
        // File.Delete(pngPath);
    }
}
