using System;
using System.IO;
using Aspose.Words;

public class Program
{
    public static void Main()
    {
        // Create a sample PDF file.
        Document source = new Document();
        DocumentBuilder builder = new DocumentBuilder(source);
        builder.Writeln("Sample PDF content generated by Aspose.Words.");
        const string pdfPath = "sample.pdf";
        source.Save(pdfPath, SaveFormat.Pdf);

        // Load the PDF and convert it to DOCX.
        Document pdfDoc = new Document(pdfPath);
        const string docxPath = "output.docx";
        pdfDoc.Save(docxPath, SaveFormat.Docx);

        // Verify that the DOCX file was created.
        if (!File.Exists(docxPath))
            throw new InvalidOperationException("The DOCX output file was not created.");

        // Optional: clean up the intermediate PDF if not needed.
        // File.Delete(pdfPath);
    }
}
