using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Define file paths in the current directory.
        string pdfPath = Path.Combine(Directory.GetCurrentDirectory(), "Sample.pdf");
        string pngPath = Path.Combine(Directory.GetCurrentDirectory(), "Sample.png");

        // -----------------------------------------------------------------
        // Step 1: Create a simple PDF document to act as the source file.
        // -----------------------------------------------------------------
        Document createDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(createDoc);
        builder.Writeln("This is a sample PDF document generated by Aspose.Words.");
        builder.Writeln("It will be converted to a high‑resolution PNG image.");
        // Save the document as PDF.
        createDoc.Save(pdfPath, SaveFormat.Pdf);

        // Verify that the PDF was created.
        if (!File.Exists(pdfPath) || new FileInfo(pdfPath).Length == 0)
            throw new InvalidOperationException("Failed to create the source PDF file.");

        // -----------------------------------------------------------------
        // Step 2: Load the PDF and convert it to a high‑resolution PNG.
        // -----------------------------------------------------------------
        Document pdfDoc = new Document(pdfPath);

        // Configure image save options for high resolution.
        ImageSaveOptions pngOptions = new ImageSaveOptions(SaveFormat.Png)
        {
            // Set DPI (dots per inch). 300 DPI is typical for detailed analysis.
            Resolution = 300,
            // Enable high‑quality rendering algorithms.
            UseHighQualityRendering = true
        };

        // Save the first page of the PDF as a PNG image.
        pdfDoc.Save(pngPath, pngOptions);

        // -----------------------------------------------------------------
        // Step 3: Validate that the PNG image was created successfully.
        // -----------------------------------------------------------------
        if (!File.Exists(pngPath) || new FileInfo(pngPath).Length == 0)
            throw new InvalidOperationException("The PNG image was not created or is empty.");

        // Optional: Output the result paths (no interactive input required).
        Console.WriteLine($"PDF created at: {pdfPath}");
        Console.WriteLine($"High‑resolution PNG created at: {pngPath}");
    }
}
