using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Loading;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Step 1: Create a simple document and save it as a PDF.
        Document sourceDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(sourceDoc);
        builder.Writeln("Sample PDF content generated by Aspose.Words.");
        const string pdfPath = "sample.pdf";
        sourceDoc.Save(pdfPath, SaveFormat.Pdf);

        // Step 2: Load the PDF using PdfLoadOptions (no password is set, so any password protection is ignored).
        PdfLoadOptions loadOptions = new PdfLoadOptions(); // Password property left null.
        Document pdfDoc = new Document(pdfPath, loadOptions);

        // Step 3: Save the loaded document as DOCX.
        const string docxPath = "output.docx";
        pdfDoc.Save(docxPath, SaveFormat.Docx);

        // Step 4: Verify that the DOCX file was created.
        if (!File.Exists(docxPath))
            throw new InvalidOperationException("The DOCX output file was not created.");

        // Optional: Inform the user that the conversion succeeded.
        Console.WriteLine($"PDF '{pdfPath}' was successfully converted to DOCX '{docxPath}'.");
    }
}
