using System;
using System.IO;
using Aspose.Words;

class ConvertPdfToXps
{
    static void Main()
    {
        // Create temporary directories for input and output files.
        string tempDir = Path.Combine(Path.GetTempPath(), "AsposeDemo");
        Directory.CreateDirectory(tempDir);

        // Path to the source PDF file.
        string pdfPath = Path.Combine(tempDir, "document.pdf");

        // Path where the XPS file will be saved.
        string xpsPath = Path.Combine(tempDir, "document.xps");

        // -----------------------------------------------------------------
        // Create a simple PDF file if it does not already exist.
        // This allows the example to run without requiring external files.
        // -----------------------------------------------------------------
        if (!File.Exists(pdfPath))
        {
            Document tempDoc = new Document();
            DocumentBuilder builder = new DocumentBuilder(tempDoc);
            builder.Writeln("This is a sample PDF generated by Aspose.Words.");
            tempDoc.Save(pdfPath, SaveFormat.Pdf);
        }

        // Load the PDF document.
        Document doc = new Document(pdfPath);

        // Save the document in XPS format for Windows XPS Viewer compatibility.
        doc.Save(xpsPath, SaveFormat.Xps);

        Console.WriteLine($"PDF file: {pdfPath}");
        Console.WriteLine($"XPS file: {xpsPath}");
        Console.WriteLine("Conversion completed successfully.");
    }
}
