using System;
using System.IO;
using Aspose.Words;

public class Program
{
    public static void Main()
    {
        // Create a sample document and save it as PDF.
        Document source = new Document();
        DocumentBuilder builder = new DocumentBuilder(source);
        builder.Writeln("Sample PDF content generated by Aspose.Words.");
        const string pdfPath = "sample.pdf";
        source.Save(pdfPath, SaveFormat.Pdf);

        // Load the PDF and convert it to XPS.
        Document pdfDoc = new Document(pdfPath);
        const string xpsPath = "output.xps";
        pdfDoc.Save(xpsPath, SaveFormat.Xps);

        // Verify that the XPS file was created.
        if (!File.Exists(xpsPath))
            throw new InvalidOperationException("The XPS file was not created.");

        // Optional cleanup of the intermediate PDF.
        if (File.Exists(pdfPath))
            File.Delete(pdfPath);
    }
}
