using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

public class Program
{
    public static void Main()
    {
        // Create a sample document.
        Document doc = new Document();
        DocumentBuilder builder = new DocumentBuilder(doc);
        builder.Writeln("This is a PDF/UA compliant document generated by Aspose.Words.");

        // Configure PDF save options for PDF/UA compliance.
        PdfSaveOptions saveOptions = new PdfSaveOptions
        {
            // Use the correct enum value for PDF/UA compliance.
            Compliance = PdfCompliance.PdfUa1
        };

        string outputPath = "output_pdfua.pdf";

        // Save the document as PDF/UA.
        doc.Save(outputPath, saveOptions);

        // Validate that the file was created and is not empty.
        if (!File.Exists(outputPath))
        {
            throw new InvalidOperationException("PDF/UA output file was not created.");
        }

        FileInfo info = new FileInfo(outputPath);
        if (info.Length == 0)
        {
            throw new InvalidOperationException("PDF/UA output file is empty.");
        }

        Console.WriteLine($"PDF/UA file successfully created at '{Path.GetFullPath(outputPath)}' (size: {info.Length} bytes).");
    }
}
