using System;
using System.Collections.Generic;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;

namespace SplitDocumentExample
{
    // Callback to capture the names of the split parts.
    public class PartSavingCallback : IDocumentPartSavingCallback
    {
        public readonly List<string> PartFileNames = new();

        void IDocumentPartSavingCallback.DocumentPartSaving(DocumentPartSavingArgs args)
        {
            // Use the default file name generated by Aspose.Words.
            string partFileName = args.DocumentPartFileName;

            // Store the part name for later verification.
            PartFileNames.Add(partFileName);

            // Optionally, you could redirect the part to a custom stream here.
            // For this example we keep the default file-based saving.
        }
    }

    public class Program
    {
        public static void Main()
        {
            // Define output folder.
            string outputDir = Path.Combine(Directory.GetCurrentDirectory(), "Output");
            Directory.CreateDirectory(outputDir);

            // Create a sample document with headings that start on new pages.
            Document doc = new Document();
            DocumentBuilder builder = new DocumentBuilder(doc);

            // First heading.
            builder.ParagraphFormat.StyleIdentifier = StyleIdentifier.Heading1;
            builder.ParagraphFormat.PageBreakBefore = true; // Ensure heading starts on a new page.
            builder.Writeln("Chapter 1");

            // Some body text.
            builder.ParagraphFormat.StyleIdentifier = StyleIdentifier.Normal;
            builder.ParagraphFormat.PageBreakBefore = false;
            builder.Writeln("Content of chapter 1.");
            builder.Writeln("More content of chapter 1.");

            // Second heading.
            builder.ParagraphFormat.StyleIdentifier = StyleIdentifier.Heading1;
            builder.ParagraphFormat.PageBreakBefore = true;
            builder.Writeln("Chapter 2");

            // Body text for second chapter.
            builder.ParagraphFormat.StyleIdentifier = StyleIdentifier.Normal;
            builder.ParagraphFormat.PageBreakBefore = false;
            builder.Writeln("Content of chapter 2.");
            builder.Writeln("More content of chapter 2.");

            // Third heading.
            builder.ParagraphFormat.StyleIdentifier = StyleIdentifier.Heading1;
            builder.ParagraphFormat.PageBreakBefore = true;
            builder.Writeln("Chapter 3");

            // Body text for third chapter.
            builder.ParagraphFormat.StyleIdentifier = StyleIdentifier.Normal;
            builder.Writeln("Content of chapter 3.");

            // Prepare HTML save options to split by heading paragraphs and page breaks.
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html)
            {
                DocumentSplitCriteria = DocumentSplitCriteria.HeadingParagraph | DocumentSplitCriteria.PageBreak,
                DocumentSplitHeadingLevel = 1 // Split at Heading 1 level.
            };

            // Attach the callback to capture part file names.
            PartSavingCallback callback = new PartSavingCallback();
            saveOptions.DocumentPartSavingCallback = callback;

            // Save the document; this will produce multiple HTML files.
            string mainFilePath = Path.Combine(outputDir, "CombinedDocument.html");
            doc.Save(mainFilePath, saveOptions);

            // Verify that split parts were created.
            Console.WriteLine($"Main file saved to: {mainFilePath}");
            Console.WriteLine($"Number of split parts: {callback.PartFileNames.Count}");
            for (int i = 0; i < callback.PartFileNames.Count; i++)
            {
                string partPath = Path.Combine(outputDir, callback.PartFileNames[i]);
                Console.WriteLine($"Part {i + 1}: {partPath} (Exists: {File.Exists(partPath)})");
            }

            // Simple validation: ensure at least one split part exists.
            if (callback.PartFileNames.Count == 0)
                throw new InvalidOperationException("No document parts were generated.");

            // End of example.
        }
    }
}
