using Aspose.Words;
using Aspose.Words.Saving;
using System;
using System.IO;

class SplitByHeading
{
    static void Main()
    {
        // Load the source DOCX document.
        Document doc = new Document("Input.docx");

        // Configure HTML save options to split the document at heading paragraphs.
        HtmlSaveOptions options = new HtmlSaveOptions();
        options.DocumentSplitCriteria = DocumentSplitCriteria.HeadingParagraph;

        // Assign a callback to give each split part a distinct file name.
        options.DocumentPartSavingCallback = new PartNamingCallback("SplitDocument.html");

        // Save the document; Aspose.Words will create multiple HTML files,
        // each containing the content of a heading section.
        doc.Save("SplitDocument.html", options);
    }

    // Callback that renames each split part generated by the save operation.
    private class PartNamingCallback : IDocumentPartSavingCallback
    {
        private readonly string _baseFileName;
        private int _partCounter;

        public PartNamingCallback(string baseFileName)
        {
            _baseFileName = baseFileName;
        }

        void IDocumentPartSavingCallback.DocumentPartSaving(DocumentPartSavingArgs args)
        {
            // Build a new file name: base name + part index + original extension.
            string extension = Path.GetExtension(args.DocumentPartFileName);
            string newFileName = $"{Path.GetFileNameWithoutExtension(_baseFileName)}_part{++_partCounter}{extension}";
            args.DocumentPartFileName = newFileName;
        }
    }
}
