using System;
using System.Data;
using Aspose.Words;
using Aspose.Words.MailMerging;

namespace OfficeMathMailMergeDemo
{
    // Custom callback that inserts OfficeMath (equation) content during mail merge.
    class OfficeMathMergingCallback : IFieldMergingCallback
    {
        // This method is called for each merge field.
        void IFieldMergingCallback.FieldMerging(FieldMergingArgs args)
        {
            // We only handle the field named "Equation".
            if (args.DocumentFieldName.Equals("Equation", StringComparison.OrdinalIgnoreCase))
            {
                // The value supplied for the field is the OMML (Office Math Markup Language) string.
                // Instead of inserting the raw text, we replace the merge field with an actual
                // OfficeMath node. Aspose.Words can parse the OMML string via the DocumentBuilder
                // method InsertHtml when the string is wrapped in a <m:oMath> element.
                // Build the full OMML fragment.
                string omml = args.FieldValue as string;
                if (!string.IsNullOrEmpty(omml))
                {
                    // Create a temporary DocumentBuilder positioned at the start of the field.
                    DocumentBuilder builder = new DocumentBuilder(args.Document);
                    builder.MoveToMergeField(args.DocumentFieldName);

                    // Insert the OMML as a node. The InsertHtml method recognises the <m:oMath> tag
                    // and creates an OfficeMath node in the document.
                    builder.InsertHtml(omml);

                    // Tell the mail‑merge engine that we have already handled the insertion.
                    args.Text = string.Empty;
                }
            }
        }

        // No special handling for image fields.
        void IFieldMergingCallback.ImageFieldMerging(ImageFieldMergingArgs args) { }
    }

    class Program
    {
        static void Main()
        {
            // 1. Create a simple template document that contains a MERGEFIELD for the equation.
            Document template = new Document();
            DocumentBuilder tmplBuilder = new DocumentBuilder(template);
            tmplBuilder.Writeln("The following equation is generated by mail merge:");
            tmplBuilder.InsertField("MERGEFIELD Equation \\* MERGEFORMAT");
            tmplBuilder.Writeln(); // Ensure there is a paragraph after the field.

            // 2. Prepare the data source. The OMML string represents the equation
            //    a + b = c (simple example). Any valid OMML can be used.
            string ommlEquation =
                @"<m:oMath xmlns:m=""http://schemas.openxmlformats.org/officeDocument/2006/math"">" +
                @"  <m:r>" +
                @"    <m:t>a</m:t>" +
                @"  </m:r>" +
                @"  <m:plus/>" +
                @"  <m:r>" +
                @"    <m:t>b</m:t>" +
                @"  </m:r>" +
                @"  <m:eq/>" +
                @"  <m:r>" +
                @"    <m:t>c</m:t>" +
                @"  </m:r>" +
                @"</m:oMath>";

            // Use a DataTable as the mail‑merge data source.
            DataTable data = new DataTable();
            data.Columns.Add("Equation", typeof(string));
            data.Rows.Add(ommlEquation);

            // 3. Set the custom field‑merging callback.
            template.MailMerge.FieldMergingCallback = new OfficeMathMergingCallback();

            // 4. Execute the mail merge.
            template.MailMerge.Execute(data);

            // 5. Save the resulting document.
            template.Save("OfficeMathMailMergeResult.docx");
        }
    }
}
