using System;
using System.Collections.Generic;
using Aspose.Words;
using Aspose.Words.Reporting;

public class Program
{
    public static void Main()
    {
        // Create a simple template document with a foreach loop and a link tag.
        Document template = new Document();
        DocumentBuilder builder = new DocumentBuilder(template);

        builder.Writeln("Links generated by LINQ Reporting:");
        builder.Writeln("<<foreach [item in Items]>>");
        // The second expression (display text) is optional; if it is null or empty,
        // the link tag will use the URL itself as the display text.
        builder.Writeln("- <<link [item.Url] [item.Text]>>");
        builder.Writeln("<</foreach>>");

        // Save the template to disk and reload it to satisfy the lifecycle rule.
        const string templatePath = "Template.docx";
        template.Save(templatePath);
        Document doc = new Document(templatePath);

        // Prepare the data model.
        ReportModel model = new ReportModel
        {
            Items = new List<LinkItem>
            {
                new LinkItem
                {
                    Url = "https://www.example.com",
                    Text = "Example Site"
                },
                new LinkItem
                {
                    Url = "https://www.google.com",
                    Text = null // No display text; the URL will be used as the link text.
                }
            }
        };

        // Build the report using the ReportingEngine.
        ReportingEngine engine = new ReportingEngine();
        engine.BuildReport(doc, model, "model");

        // Save the generated report.
        const string outputPath = "Report.docx";
        doc.Save(outputPath);
    }
}

// Root data model referenced by the template (root name: "model").
public class ReportModel
{
    public List<LinkItem> Items { get; set; } = new();
}

// Individual item containing a URL and an optional display text.
public class LinkItem
{
    public string Url { get; set; } = string.Empty;
    public string? Text { get; set; }
}
