using System;
using System.Collections.Generic;
using Aspose.Words;
using Aspose.Words.Reporting;
using Aspose.Words.Drawing;
using Aspose.Words.Tables;

namespace LinqReportingMultiSection
{
    // Header data model
    public class HeaderModel
    {
        public string Title { get; set; } = "Multi‑Section Report";
        public DateTime Date { get; set; } = DateTime.Now;
    }

    // Body item model
    public class BodyItem
    {
        public int Index { get; set; }
        public string Description { get; set; } = string.Empty;
    }

    // Body data model (contains a collection)
    public class BodyModel
    {
        public List<BodyItem> Items { get; set; } = new();
    }

    // Footer data model
    public class FooterModel
    {
        public string FooterText { get; set; } = "Confidential – Generated by Aspose.Words";
    }

    public class Program
    {
        public static void Main()
        {
            // -----------------------------------------------------------------
            // 1. Create the template document programmatically.
            // -----------------------------------------------------------------
            var templatePath = "Template.docx";

            var templateDoc = new Document();
            var builder = new DocumentBuilder(templateDoc);

            // Section 1 – Header
            builder.Writeln("<<[header.Title]>>");
            builder.Writeln("Date: <<[header.Date]>>");
            builder.InsertBreak(BreakType.SectionBreakNewPage);

            // Section 2 – Body (foreach loop)
            builder.Writeln("<<foreach [item in body.Items]>>");
            builder.Writeln("Item <<[item.Index]>>: <<[item.Description]>>");
            builder.Writeln("<</foreach>>");
            builder.InsertBreak(BreakType.SectionBreakNewPage);

            // Section 3 – Footer
            builder.Writeln("<<[footer.FooterText]>>");

            // Save the template to disk.
            templateDoc.Save(templatePath);

            // -----------------------------------------------------------------
            // 2. Load the template for reporting.
            // -----------------------------------------------------------------
            var reportDoc = new Document(templatePath);

            // -----------------------------------------------------------------
            // 3. Prepare data sources.
            // -----------------------------------------------------------------
            var header = new HeaderModel();

            var body = new BodyModel();
            for (int i = 1; i <= 5; i++)
            {
                body.Items.Add(new BodyItem
                {
                    Index = i,
                    Description = $"Description of item {i}"
                });
            }

            var footer = new FooterModel();

            // -----------------------------------------------------------------
            // 4. Build the report using multiple data sources.
            // -----------------------------------------------------------------
            var engine = new ReportingEngine();
            engine.BuildReport(
                reportDoc,
                new object[] { header, body, footer },
                new[] { "header", "body", "footer" });

            // -----------------------------------------------------------------
            // 5. Save the generated report.
            // -----------------------------------------------------------------
            var outputPath = "MultiSectionReport.docx";
            reportDoc.Save(outputPath);
        }
    }
}
