using System;
using System.Collections.Generic;
using Aspose.Words;
using Aspose.Words.Reporting;

namespace LinqReportingExample
{
    public class HeaderInfo
    {
        public string Title { get; set; } = "";
        public string Date { get; set; } = "";
    }

    public class Product
    {
        public string Name { get; set; } = "";
        public int Quantity { get; set; }
    }

    public class BodyInfo
    {
        public List<Product> Items { get; set; } = new();
    }

    public class FooterInfo
    {
        public string Note { get; set; } = "";
    }

    public class ReportModel
    {
        public HeaderInfo Header { get; set; } = new();
        public BodyInfo Body { get; set; } = new();
        public FooterInfo Footer { get; set; } = new();
    }

    public class Program
    {
        public static void Main()
        {
            // Create the template document.
            var templatePath = "Template.docx";
            var templateDoc = new Document();
            var builder = new DocumentBuilder(templateDoc);

            // Header section.
            builder.Writeln("<<[Header.Title]>>");
            builder.Writeln("Date: <<[Header.Date]>>");
            builder.Writeln("");

            // Body section with a product list.
            builder.Writeln("Products:");
            builder.Writeln("<<foreach [p in Body.Items]>>");
            builder.Writeln("- <<[p.Name]>>: <<[p.Quantity]>>");
            builder.Writeln("<</foreach>>");
            builder.Writeln("");

            // Footer section.
            builder.Writeln("<<[Footer.Note]>>");

            // Save the template.
            templateDoc.Save(templatePath);

            // Load the template for report generation.
            var reportDoc = new Document(templatePath);

            // Prepare sample data.
            var model = new ReportModel
            {
                Header = new HeaderInfo
                {
                    Title = "Monthly Sales Report",
                    Date = DateTime.Now.ToString("MMMM yyyy")
                },
                Body = new BodyInfo
                {
                    Items = new List<Product>
                    {
                        new Product { Name = "Widget A", Quantity = 120 },
                        new Product { Name = "Widget B", Quantity = 85 },
                        new Product { Name = "Widget C", Quantity = 47 }
                    }
                },
                Footer = new FooterInfo
                {
                    Note = "Generated by Aspose.Words LINQ Reporting Engine"
                }
            };

            // Build the report.
            var engine = new ReportingEngine();
            engine.BuildReport(reportDoc, model, "model");

            // Save the final report.
            var outputPath = "Report.docx";
            reportDoc.Save(outputPath);
        }
    }
}
