using System;
using System.Collections.Generic;
using Aspose.Words;
using Aspose.Words.Reporting;

public class Program
{
    public static void Main()
    {
        // -----------------------------------------------------------------
        // 1. Bootstrap sample data.
        // -----------------------------------------------------------------
        var model = new ReportModel
        {
            Items = new List<Item>
            {
                new Item { Url = "https://example.com", Text = "Example Site" },
                new Item { Url = "", Text = "Missing URL" } // This entry will trigger an error log.
            }
        };

        // Log empty hyperlink targets before report generation.
        foreach (var item in model.Items)
        {
            if (string.IsNullOrWhiteSpace(item.Url))
                Console.WriteLine($"Error: Hyperlink target is empty for item with text \"{item.Text}\".");
        }

        // -----------------------------------------------------------------
        // 2. Create the template document programmatically.
        // -----------------------------------------------------------------
        var template = new Document();
        var builder = new DocumentBuilder(template);

        builder.Writeln("Report generated by Aspose.Words LINQ Reporting");
        builder.Writeln("<<foreach [item in Items]>>");
        // Emit a link only when the URL is not empty.
        builder.Writeln("<<if [item.Url]>><<link [item.Url] [item.Text]>> <</if>>");
        builder.Writeln("<</foreach>>");

        // Save the template, then reload it as required by the workflow.
        const string templatePath = "Template.docx";
        template.Save(templatePath);
        var loadedTemplate = new Document(templatePath);

        // -----------------------------------------------------------------
        // 3. Build the report using the ReportingEngine.
        // -----------------------------------------------------------------
        var engine = new ReportingEngine();
        engine.Options = ReportBuildOptions.InlineErrorMessages; // Inline error messages enabled.
        bool success = engine.BuildReport(loadedTemplate, model, "model");

        // Save the generated report.
        const string outputPath = "Report.docx";
        loadedTemplate.Save(outputPath);

        // Indicate completion.
        Console.WriteLine($"Report generation {(success ? "succeeded" : "failed")}. Output saved to \"{outputPath}\".");
    }
}

// ---------------------------------------------------------------------
// Public data model classes (must be non‑anonymous and fully accessible).
// ---------------------------------------------------------------------
public class ReportModel
{
    public List<Item> Items { get; set; } = new();
}

public class Item
{
    public string Url { get; set; } = string.Empty;
    public string Text { get; set; } = string.Empty;
}
