using System;
using System.Collections.Generic;
using Aspose.Words;
using Aspose.Words.Reporting;

namespace LinqReportingReflectionOptimization
{
    // Sample data model
    public class ReportModel
    {
        public List<Item> Items { get; set; } = new();
    }

    public class Item
    {
        public string Name { get; set; } = "";
        public int Value { get; set; }
    }

    public class Program
    {
        public static void Main()
        {
            // Paths for template and output
            const string templatePath = "Template.docx";
            const string outputPath = "Report.docx";

            // -----------------------------------------------------------------
            // 1. Create the template document programmatically
            // -----------------------------------------------------------------
            Document templateDoc = new Document();
            DocumentBuilder builder = new DocumentBuilder(templateDoc);

            // Write a simple LINQ Reporting template that iterates over Items
            builder.Writeln("Report generated by Aspose.Words LINQ Reporting");
            builder.Writeln("<<foreach [item in Items]>>");
            builder.Writeln("Item: <<[item.Name]>> - Value: <<[item.Value]>>");
            builder.Writeln("<</foreach>>");

            // Save the template to disk
            templateDoc.Save(templatePath);

            // -----------------------------------------------------------------
            // 2. Load the template back (required before building the report)
            // -----------------------------------------------------------------
            Document doc = new Document(templatePath);

            // -----------------------------------------------------------------
            // 3. Prepare sample data (fewer than 1,000 records)
            // -----------------------------------------------------------------
            ReportModel model = new()
            {
                Items = new()
                {
                    new Item { Name = "Alpha",   Value = 10 },
                    new Item { Name = "Beta",    Value = 20 },
                    new Item { Name = "Gamma",   Value = 30 },
                    new Item { Name = "Delta",   Value = 40 },
                    new Item { Name = "Epsilon", Value = 50 }
                }
            };

            // -----------------------------------------------------------------
            // 4. Configure reflection optimization based on record count
            // -----------------------------------------------------------------
            // Disable optimization when processing fewer than 1,000 records
            ReportingEngine.UseReflectionOptimization = model.Items.Count >= 1000;

            // -----------------------------------------------------------------
            // 5. Build the report
            // -----------------------------------------------------------------
            ReportingEngine engine = new ReportingEngine();
            engine.BuildReport(doc, model, "model");

            // -----------------------------------------------------------------
            // 6. Save the generated report
            // -----------------------------------------------------------------
            doc.Save(outputPath);
        }
    }
}
