using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Aspose.Words;
using Aspose.Words.Reporting;

namespace AsposeWordsLinqReporting
{
    // Simple data model with a collection of items.
    public class ReportModel
    {
        public List<Item> Items { get; set; } = new();
    }

    public class Item
    {
        public string Name { get; set; } = string.Empty;
        public int Value { get; set; }
    }

    public class Program
    {
        public static void Main()
        {
            // Register code page provider for any legacy encodings used by Aspose.Words.
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

            // Paths for the template and the generated report.
            string templatePath = "Template.docx";
            string outputPath = "Report.docx";

            // -----------------------------------------------------------------
            // 1. Create a template document with LINQ Reporting tags.
            // -----------------------------------------------------------------
            Document templateDoc = new Document();
            DocumentBuilder builder = new DocumentBuilder(templateDoc);

            // Write a simple foreach loop that will list all items.
            builder.Writeln("Report generated by Aspose.Words LINQ Reporting");
            builder.Writeln("<<foreach [item in Items]>>");
            builder.Writeln("Item: <<[item.Name]>> - Value: <<[item.Value]>>");
            builder.Writeln("<</foreach>>");

            // Save the template to disk.
            templateDoc.Save(templatePath);

            // -----------------------------------------------------------------
            // 2. Prepare sample data (less than 1000 records).
            // -----------------------------------------------------------------
            ReportModel model = new ReportModel();
            for (int i = 1; i <= 5; i++)
            {
                model.Items.Add(new Item { Name = $"Item{i}", Value = i * 10 });
            }

            // -----------------------------------------------------------------
            // 3. Configure the ReportingEngine.
            //    Disable reflection optimization when the record count is < 1000.
            // -----------------------------------------------------------------
            // Determine record count (number of items).
            int recordCount = model.Items.Count;

            // Set the static property accordingly.
            ReportingEngine.UseReflectionOptimization = recordCount >= 1000;

            // Create the engine instance.
            ReportingEngine engine = new ReportingEngine();

            // Load the template document (could reuse the one already in memory, but the rule suggests loading).
            Document doc = new Document(templatePath);

            // Build the report using the model as the root object named "model".
            engine.BuildReport(doc, model, "model");

            // -----------------------------------------------------------------
            // 4. Save the generated report.
            // -----------------------------------------------------------------
            doc.Save(outputPath);
        }
    }
}
