using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Reporting;

public class ReportModel
{
    // URL of the external website.
    public string Url { get; set; } = "https://www.example.com";

    // Text that will be displayed for the hyperlink.
    public string LinkText { get; set; } = "Visit Example";
}

public class Program
{
    public static void Main()
    {
        // Paths for the template and the generated report.
        const string templatePath = "template.docx";
        const string outputPath = "output.docx";

        // -----------------------------------------------------------------
        // 1. Create the LINQ Reporting template programmatically.
        // -----------------------------------------------------------------
        Document templateDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(templateDoc);

        // Add some introductory text.
        builder.Writeln("Below is a hyperlink generated by LINQ Reporting:");

        // Insert the link tag. The tag uses the model name "model" as the root.
        builder.Writeln("<<link [model.Url] [model.LinkText]>>");

        // Save the template to disk.
        templateDoc.Save(templatePath);

        // -----------------------------------------------------------------
        // 2. Load the template and build the report.
        // -----------------------------------------------------------------
        Document reportDoc = new Document(templatePath);

        // Prepare the data model.
        ReportModel model = new ReportModel();

        // Create the reporting engine and generate the report.
        ReportingEngine engine = new ReportingEngine();
        engine.BuildReport(reportDoc, model, "model");

        // -----------------------------------------------------------------
        // 3. Save the generated document.
        // -----------------------------------------------------------------
        reportDoc.Save(outputPath);
    }
}
