using System;
using System.Collections.Generic;
using Aspose.Words;
using Aspose.Words.Reporting;

namespace LinqReportingDemo
{
    public class Program
    {
        public static void Main()
        {
            // Prepare sample data model.
            var model = new ReportModel
            {
                Items = new List<Item>
                {
                    new Item { Index = 1, Name = "Apple" },
                    new Item { Index = 2, Name = "Banana" },
                    new Item { Index = 3, Name = "Cherry" }
                }
            };

            // Create a template document with LINQ Reporting tags.
            var template = new Document();
            var builder = new DocumentBuilder(template);
            builder.Writeln("Report generated by LINQ Reporting:");
            builder.Writeln("<<foreach [item in Items]>>");
            builder.Writeln("Item <<[item.Index]>>: <<[item.Name]>>");
            builder.Writeln("<</foreach>>");

            // Save the template to a file.
            const string templatePath = "Template.docx";
            template.Save(templatePath);

            // Load the template for report generation.
            var doc = new Document(templatePath);

            // Build the report using the data model.
            var engine = new ReportingEngine();
            engine.BuildReport(doc, model, "model");

            // Save the final report.
            const string reportPath = "Report.docx";
            doc.Save(reportPath);
        }
    }

    // Root data model referenced by the template.
    public class ReportModel
    {
        public List<Item> Items { get; set; } = new();
    }

    // Item type used in the collection; the engine determines this type automatically.
    public class Item
    {
        public int Index { get; set; }
        public string Name { get; set; } = string.Empty;
    }
}
