using System;
using System.Collections.Generic;
using Aspose.Words;
using Aspose.Words.Reporting;

public class Program
{
    public static void Main()
    {
        // -------------------- Create template --------------------
        Document template = new Document();
        DocumentBuilder builder = new DocumentBuilder(template);

        builder.Writeln("Report generated by LINQ Reporting:");
        builder.Writeln("<<foreach [item in Items]>>");
        builder.Writeln("Item: <<[item.Index]>> - <<[item.Name]>>");
        builder.Writeln("<</foreach>>");

        const string templatePath = "Template.docx";
        template.Save(templatePath); // Save the template to disk

        // -------------------- Load template --------------------
        Document report = new Document(templatePath);

        // -------------------- Prepare data --------------------
        List<Item> items = new()
        {
            new Item { Index = 1, Name = "Apple" },
            new Item { Index = 2, Name = "Banana" },
            new Item { Index = 3, Name = "Cherry" }
        };

        ReportModel model = new()
        {
            Items = items // Strongly‑typed collection
        };

        // -------------------- Build report --------------------
        ReportingEngine engine = new ReportingEngine();
        engine.Options = ReportBuildOptions.None;

        // Register the item type so the engine can resolve members on objects of type Item
        engine.KnownTypes.Add(typeof(Item));

        engine.BuildReport(report, model, "model");

        // -------------------- Save output --------------------
        const string outputPath = "Report.docx";
        report.Save(outputPath);
    }
}

// Simple data item class.
public class Item
{
    public int Index { get; set; } = 0;
    public string Name { get; set; } = string.Empty;
}

// Wrapper model exposing a strongly‑typed IEnumerable<Item>.
public class ReportModel
{
    public IEnumerable<Item> Items { get; set; } = new List<Item>();
}
