using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Reporting;

public class Program
{
    public static void Main()
    {
        // Working directory.
        string workDir = Directory.GetCurrentDirectory();

        // Create sample HTML fragments.
        string newsHtmlPath = Path.Combine(workDir, "news.html");
        File.WriteAllText(newsHtmlPath, "<h1>News Section</h1><p>This is the news content.</p>");

        string sportsHtmlPath = Path.Combine(workDir, "sports.html");
        File.WriteAllText(sportsHtmlPath, "<h1>Sports Section</h1><p>This is the sports content.</p>");

        // Create the LINQ Reporting template.
        string templatePath = Path.Combine(workDir, "template.docx");
        Document templateDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(templateDoc);

        // Title.
        builder.Writeln("Report generated by Aspose.Words LINQ Reporting");
        builder.Writeln();

        // Insert the HTML fragment dynamically.
        // The expression evaluates to a string containing HTML markup.
        builder.Writeln("<<[model.HtmlFragment] -html>>");

        // Save the template.
        templateDoc.Save(templatePath);

        // Load the template for reporting.
        Document doc = new Document(templatePath);

        // Prepare the data model.
        ReportModel model = new()
        {
            // Choose which fragment to include.
            // Change this to sportsHtmlPath to include the sports fragment.
            HtmlFragment = File.ReadAllText(newsHtmlPath)
        };

        // Build the report.
        ReportingEngine engine = new ReportingEngine();
        engine.BuildReport(doc, model, "model");

        // Save the generated report.
        string outputPath = Path.Combine(workDir, "output.docx");
        doc.Save(outputPath);
    }
}

// Public data model used by the template.
public class ReportModel
{
    // HTML fragment to be inserted into the report.
    public string HtmlFragment { get; set; } = string.Empty;
}
