using System;
using System.IO;
using System.Text;
using Aspose.Words;
using Aspose.Words.Reporting;
using Aspose.Words.Tables;

public class Program
{
    public static void Main()
    {
        // Register code page provider for CSV encoding support.
        Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

        // Prepare sample CSV data.
        string csvPath = "data.csv";
        File.WriteAllText(csvPath,
@"Name,Value
Alice,100
Bob,200

Charlie,
,300
David,400");

        // Create a template document programmatically.
        string templatePath = "template.docx";
        var templateDoc = new Document();
        var builder = new DocumentBuilder(templateDoc);

        // Static header.
        builder.Writeln("Report Header");
        // Keep a blank line after the header (non‑breaking space).
        builder.Writeln("\u00A0");

        // CSV section using LINQ Reporting tags.
        builder.Writeln("<<foreach [row in csv]>>");
        builder.Writeln("<<[row.Name]>> <<[row.Value]>>");
        builder.Writeln("<</foreach>>");
        // Keep a blank line after the CSV section.
        builder.Writeln("\u00A0");

        // Static footer.
        builder.Writeln("Report Footer");

        // Save the template.
        templateDoc.Save(templatePath);

        // Load the template for report generation.
        var doc = new Document(templatePath);

        // Create CSV data source with header support.
        var csvLoadOptions = new CsvDataLoadOptions { HasHeaders = true };
        var csvDataSource = new CsvDataSource(csvPath, csvLoadOptions);

        // Build the report.
        var engine = new ReportingEngine();
        engine.BuildReport(doc, csvDataSource, "csv");

        // Remove empty paragraphs generated by the CSV processing.
        // Paragraphs containing only a non‑breaking space are kept.
        var paragraphs = doc.GetChildNodes(NodeType.Paragraph, true);
        for (int i = paragraphs.Count - 1; i >= 0; i--)
        {
            var paragraph = (Paragraph)paragraphs[i];
            if (string.IsNullOrWhiteSpace(paragraph.GetText()))
                paragraph.Remove();
        }

        // Save the final document.
        string outputPath = "output.docx";
        doc.Save(outputPath);
    }
}
