using System;
using System.Collections.Generic;
using System.IO;
using Aspose.Words;
using Aspose.Words.Reporting;

public class Program
{
    public static void Main()
    {
        // Ensure the output directory exists.
        string outputDir = Path.Combine(Directory.GetCurrentDirectory(), "Output");
        Directory.CreateDirectory(outputDir);

        // Step 1: Create a template document with LINQ Reporting tags.
        Document template = new Document();
        DocumentBuilder builder = new DocumentBuilder(template);

        builder.Writeln("Report generated by Aspose.Words LINQ Reporting");
        builder.Writeln("<<foreach [item in Items]>>");
        builder.Writeln("Name: <<[item.Name]>>");
        // Conditional paragraph that may become empty if Description is null or empty.
        builder.Writeln("<<if [item.Description != null && item.Description != \"\"]>>");
        builder.Writeln("Description: <<[item.Description]>>");
        builder.Writeln("<</if>>");
        builder.Writeln("<</foreach>>");

        // Save the template to disk.
        string templatePath = Path.Combine(outputDir, "Template.docx");
        template.Save(templatePath);

        // Step 2: Load the template for processing.
        Document reportDoc = new Document(templatePath);

        // Step 3: Prepare sample data with some empty descriptions.
        ReportModel model = new ReportModel
        {
            Items = new List<Item>
            {
                new Item { Name = "Item A", Description = "First item description." },
                new Item { Name = "Item B", Description = "" },               // Empty description.
                new Item { Name = "Item C", Description = null },            // Null description.
                new Item { Name = "Item D", Description = "Fourth item." }
            }
        };

        // Step 4: Build the report with the option to remove empty paragraphs.
        ReportingEngine engine = new ReportingEngine();
        engine.Options = ReportBuildOptions.RemoveEmptyParagraphs;
        engine.BuildReport(reportDoc, model, "model");

        // Step 5: Save the final document.
        string resultPath = Path.Combine(outputDir, "Report.docx");
        reportDoc.Save(resultPath);
    }
}

// Root data model aligned with the template tags.
public class ReportModel
{
    public List<Item> Items { get; set; } = new();
}

// Simple item class used in the report.
public class Item
{
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
}
