using System;
using System.Collections.Generic;
using Aspose.Words;
using Aspose.Words.Reporting;

namespace AsposeWordsLinqReporting
{
    // Data model used by the template.
    public class ReportModel
    {
        public List<Item> Items { get; set; } = new();
    }

    public class Item
    {
        public string Name { get; set; } = string.Empty;
        public string? Description { get; set; }
    }

    public class Program
    {
        public static void Main()
        {
            // Create a blank document and a builder to insert the template tags.
            Document doc = new Document();
            DocumentBuilder builder = new DocumentBuilder(doc);

            // Simple header.
            builder.Writeln("Report generated by Aspose.Words LINQ Reporting");

            // Begin a foreach block over Items.
            builder.Writeln("<<foreach [item in Items]>>");
            // Paragraph that will contain a name.
            builder.Writeln("Name: <<[item.Name]>>");
            // Paragraph that may become empty if Description is null.
            builder.Writeln("Description: <<[item.Description]>>");
            // End the foreach block.
            builder.Writeln("<</foreach>>");

            // Prepare sample data: one item without a description (null) and one with a description.
            ReportModel model = new()
            {
                Items = new List<Item>
                {
                    new Item { Name = "Item A", Description = null },
                    new Item { Name = "Item B", Description = "This is a description." }
                }
            };

            // Configure the reporting engine to remove empty paragraphs after processing.
            ReportingEngine engine = new ReportingEngine
            {
                Options = ReportBuildOptions.RemoveEmptyParagraphs
            };

            // Build the report using the model. The root object name is "model".
            engine.BuildReport(doc, model, "model");

            // Save the resulting document.
            doc.Save("ReportOutput.docx");
        }
    }
}
