using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Reporting;

public class Program
{
    public static void Main()
    {
        // Ensure the output directory exists.
        string outputDir = Path.Combine(Directory.GetCurrentDirectory(), "Output");
        Directory.CreateDirectory(outputDir);

        // Create a new blank document.
        Document doc = new Document();
        DocumentBuilder builder = new DocumentBuilder(doc);

        // Build a template with required and optional sections.
        // Required field – will be present.
        builder.Writeln("Customer: <<[model.CustomerName]>>");

        // Optional field – does not exist in the model, will trigger an error.
        builder.Writeln("Address: <<[model.Address]>>");

        // Optional section that will display any inline error messages.
        // The <<error>> tag inserts the error message generated by the engine.
        builder.Writeln("<<error>>");

        // Prepare the data model. Only CustomerName is defined; Address is missing.
        ReportModel model = new ReportModel
        {
            CustomerName = "John Doe"
            // Address property is intentionally omitted to simulate missing data.
        };

        // Configure the reporting engine to inline error messages.
        ReportingEngine engine = new ReportingEngine();
        engine.Options = ReportBuildOptions.InlineErrorMessages;

        // Build the report. The third parameter aligns the root object name with the template tags.
        bool success = engine.BuildReport(doc, model, "model");

        // Save the generated report.
        string outputPath = Path.Combine(outputDir, "Report.docx");
        doc.Save(outputPath);

        // Output simple status information.
        Console.WriteLine($"Report generation {(success ? "succeeded" : "failed")}.");
        Console.WriteLine($"Report saved to: {outputPath}");
    }

    // Public data model class required by the template.
    public class ReportModel
    {
        // Non‑nullable reference type initialized to avoid warnings.
        public string CustomerName { get; set; } = string.Empty;
        // No Address property – this will cause a missing‑member warning.
    }
}
