using System;
using Aspose.Words;
using Aspose.Words.Reporting;

namespace AsposeWordsLinqReportingDemo
{
    // Simple data model for the report.
    public class ReportModel
    {
        // Bookmark name that will be used in the template.
        // Initialized to an empty string to trigger the warning scenario.
        public string BookmarkName { get; set; } = string.Empty;

        // Some content to place inside the bookmark.
        public string Content { get; set; } = "Sample content inside bookmark.";
    }

    public class Program
    {
        public static void Main()
        {
            // Paths for the template and the generated report.
            const string templatePath = "template.docx";
            const string outputPath = "report.docx";

            // -----------------------------------------------------------------
            // 1. Create the template document programmatically.
            // -----------------------------------------------------------------
            var templateDoc = new Document();
            var builder = new DocumentBuilder(templateDoc);

            // Insert a bookmark tag. The expression [model.BookmarkName] may evaluate to an empty string.
            builder.Writeln("<<bookmark [model.BookmarkName]>>");
            builder.Writeln("<<[model.Content]>>");
            builder.Writeln("<</bookmark>>");

            // Save the template to disk.
            templateDoc.Save(templatePath);

            // -----------------------------------------------------------------
            // 2. Load the template for reporting.
            // -----------------------------------------------------------------
            var doc = new Document(templatePath);

            // -----------------------------------------------------------------
            // 3. Prepare the data source.
            // -----------------------------------------------------------------
            var model = new ReportModel(); // BookmarkName is empty by default.

            // If the bookmark name is empty, log a warning and provide a fallback name
            // to avoid the engine throwing an exception (bookmark name must be non‑empty).
            if (string.IsNullOrEmpty(model.BookmarkName))
            {
                Console.WriteLine("Warning: The bookmark name expression evaluated to an empty string.");
                model.BookmarkName = "AutoGeneratedBookmark";
            }

            // -----------------------------------------------------------------
            // 4. Build the report using the LINQ Reporting engine.
            // -----------------------------------------------------------------
            var engine = new ReportingEngine
            {
                // Enable inline error messages so that the engine reports problems (e.g., missing members).
                Options = ReportBuildOptions.InlineErrorMessages
            };

            // BuildReport returns false when there are parsing errors.
            bool success = engine.BuildReport(doc, model, "model");

            // If the engine still reports errors, log a generic warning.
            if (!success)
            {
                Console.WriteLine("Warning: The report was built with parsing errors.");
            }

            // -----------------------------------------------------------------
            // 5. Save the generated report.
            // -----------------------------------------------------------------
            doc.Save(outputPath);
        }
    }
}
