using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Reporting;

public class Program
{
    public static void Main()
    {
        // Prepare working directory and file paths.
        string workDir = Directory.GetCurrentDirectory();
        string templatePath = Path.Combine(workDir, "Template.docx");
        string outputPath = Path.Combine(workDir, "Result.docx");

        // ---------- Create the LINQ Reporting template ----------
        Document templateDoc = new Document();
        DocumentBuilder builder = new DocumentBuilder(templateDoc);

        // Insert a bookmark tag whose name comes from the data model.
        builder.Writeln("<<bookmark [model.BookmarkName]>>");
        builder.Writeln("This is bookmarked content.");
        builder.Writeln("<</bookmark>>");

        // Save the template to disk.
        templateDoc.Save(templatePath);

        // ---------- Load the template ----------
        Document doc = new Document(templatePath);

        // ---------- Prepare the data model ----------
        ReportModel model = new()
        {
            // Intentionally empty to demonstrate warning handling.
            BookmarkName = string.Empty,
            Title = "Sample Title"
        };

        // Preserve the original bookmark name to detect emptiness later.
        string originalBookmarkName = model.BookmarkName;

        // If the bookmark name is empty, replace it with a placeholder to avoid runtime error.
        if (string.IsNullOrEmpty(originalBookmarkName))
        {
            model.BookmarkName = "AutoGeneratedBookmark";
        }

        // ---------- Configure the reporting engine ----------
        ReportingEngine engine = new ReportingEngine();
        engine.Options = ReportBuildOptions.InlineErrorMessages;

        // ---------- Build the report ----------
        bool success = engine.BuildReport(doc, model, "model");

        // Log a warning if the original bookmark name was empty.
        if (string.IsNullOrEmpty(originalBookmarkName))
        {
            Console.WriteLine("Warning: The bookmark name expression evaluated to an empty string.");
        }

        // ---------- Save the generated document ----------
        doc.Save(outputPath);
    }

    // Public data model aligned with the template.
    public class ReportModel
    {
        // Bookmark name used in the <<bookmark>> tag.
        public string BookmarkName { get; set; } = string.Empty;

        // Additional sample property (not used in this example).
        public string Title { get; set; } = string.Empty;
    }
}
