using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Aspose.Words;
using Aspose.Words.Reporting;

public class Program
{
    public static void Main()
    {
        // Prepare output directory
        string outputDir = Path.Combine(Directory.GetCurrentDirectory(), "Output");
        Directory.CreateDirectory(outputDir);

        // Create the template document
        string templatePath = Path.Combine(outputDir, "template.docx");
        Document template = new Document();
        DocumentBuilder builder = new DocumentBuilder(template);

        builder.Writeln("Report generated by Aspose.Words LINQ Reporting");
        builder.Writeln();

        // Outer foreach: categories
        builder.Writeln("<<foreach [cat in Categories]>>");
        builder.Writeln("Category: <<[cat.Name]>>");
        builder.Writeln();

        // Inner foreach: items
        builder.Writeln("<<foreach [item in cat.Items]>>");
        builder.Writeln("- <<[item.Name]>> : $<<[item.Price]>>");
        builder.Writeln("<</foreach>>");
        builder.Writeln();

        // Output subtotal for the current category
        builder.Writeln("Subtotal for <<[cat.Name]>>: $<<[cat.Subtotal]>>");
        builder.Writeln("<</foreach>>");

        // Save the template
        template.Save(templatePath);

        // Prepare sample data
        var data = new ReportRoot
        {
            Categories = new List<Category>
            {
                new Category
                {
                    Name = "Beverages",
                    Items = new List<Item>
                    {
                        new Item { Name = "Coffee", Price = 3.50m },
                        new Item { Name = "Tea", Price = 2.75m },
                        new Item { Name = "Juice", Price = 4.20m }
                    }
                },
                new Category
                {
                    Name = "Snacks",
                    Items = new List<Item>
                    {
                        new Item { Name = "Chips", Price = 1.99m },
                        new Item { Name = "Cookies", Price = 2.49m }
                    }
                }
            }
        };

        // Build the report
        ReportingEngine engine = new ReportingEngine();
        engine.BuildReport(template, data, "model");

        // Save the generated report
        string reportPath = Path.Combine(outputDir, "report.docx");
        template.Save(reportPath);

        // Inform the user (no interactive input)
        Console.WriteLine($"Report generated: {reportPath}");
    }
}

// Root object passed to the engine
public class ReportRoot
{
    public List<Category> Categories { get; set; } = new();
}

// Category model
public class Category
{
    public string Name { get; set; } = string.Empty;
    public List<Item> Items { get; set; } = new();

    // Subtotal calculated from the items collection
    public decimal Subtotal => Items.Sum(i => i.Price);
}

// Item model
public class Item
{
    public string Name { get; set; } = string.Empty;
    public decimal Price { get; set; }
}
