using System;
using System.Collections.Generic;
using Aspose.Words;
using Aspose.Words.Reporting;

namespace AsposeWordsLinqReportingDemo
{
    // Simple data item.
    public class Item
    {
        public int Index { get; set; } = 0;
        public string Name { get; set; } = string.Empty;
    }

    // Wrapper model that will be passed to the reporting engine.
    public class ReportModel
    {
        public List<Item> Items { get; set; } = new();
    }

    public class Program
    {
        public static void Main()
        {
            // Prepare sample data.
            var model = new ReportModel
            {
                Items = new List<Item>
                {
                    new Item { Index = 1, Name = "Alpha" },
                    new Item { Index = 2, Name = "Beta" },
                    new Item { Index = 3, Name = "Gamma" }
                }
            };

            // Create a template document programmatically.
            var doc = new Document();
            var builder = new DocumentBuilder(doc);

            builder.Writeln("Report generated by Aspose.Words LINQ Reporting");
            builder.Writeln(); // empty line

            // Data band: foreach over Items. Inside the band we refer to members without object reference.
            builder.Writeln("<<foreach [item in Items]>>");
            builder.Writeln("Item <<[Index]>>: <<[Name]>>");
            builder.Writeln("<</foreach>>");

            // Build the report using the model. The root object name must match the name used in the template.
            var engine = new ReportingEngine();
            engine.BuildReport(doc, model, "model");

            // Save the generated report.
            doc.Save("Report.docx");
        }
    }
}
