using System;
using System.Collections.Generic;
using System.IO;
using Aspose.Words;
using Aspose.Words.Reporting;

public class Program
{
    public static void Main()
    {
        // Ensure the required code page provider is registered (needed for some data sources).
        System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

        // Step 1: Create a template document with a LINQ Reporting foreach loop.
        Document template = new Document();
        DocumentBuilder builder = new DocumentBuilder(template);

        // The loop will iterate over Items and output each item's Text.
        builder.Writeln("<<foreach [item in Items]>>");
        // NOTE: The requested <<setAlignment>> tag is not a supported LINQ Reporting tag.
        // Instead, we will handle alignment programmatically after the report is built.
        builder.Writeln("<<[item.Text]>>");
        builder.Writeln("<</foreach>>");

        // Save the template to disk.
        const string templatePath = "Template.docx";
        template.Save(templatePath);

        // Step 2: Prepare the data model.
        ReportModel model = new ReportModel
        {
            Items = new List<Item>
            {
                new Item { Text = "First line (centered)", AlignCenter = true },
                new Item { Text = "Second line (left)", AlignCenter = false },
                new Item { Text = "Third line (centered)", AlignCenter = true }
            }
        };

        // Step 3: Load the template and build the report.
        Document report = new Document(templatePath);
        ReportingEngine engine = new ReportingEngine();
        engine.BuildReport(report, model, "model");

        // Step 4: Apply paragraph alignment based on the data.
        // The paragraphs generated by the foreach loop appear in order,
        // so we can align them by iterating through the Items collection.
        int paragraphIndex = 0;
        foreach (Paragraph paragraph in report.FirstSection.Body.Paragraphs)
        {
            // Skip empty paragraphs that may be inserted by the engine.
            if (string.IsNullOrWhiteSpace(paragraph.GetText()))
                continue;

            if (paragraphIndex < model.Items.Count)
            {
                paragraph.ParagraphFormat.Alignment = model.Items[paragraphIndex].AlignCenter
                    ? ParagraphAlignment.Center
                    : ParagraphAlignment.Left;
                paragraphIndex++;
            }
        }

        // Step 5: Save the final report.
        const string outputPath = "Report.docx";
        report.Save(outputPath);
    }
}

// Data model classes.
public class ReportModel
{
    public List<Item> Items { get; set; } = new();
}

public class Item
{
    public string Text { get; set; } = string.Empty;
    public bool AlignCenter { get; set; }
}
