using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Aspose.Words;
using Aspose.Words.Reporting;
using Newtonsoft.Json;

public class Program
{
    public static void Main()
    {
        // Register code page provider for UTF‑8 and other encodings.
        Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

        // -----------------------------------------------------------------
        // 1. Create sample JSON data.
        // -----------------------------------------------------------------
        const string jsonPath = "data.json";
        var jsonContent = @"{
  ""Items"": [
    { ""Category"": ""Fruits"", ""Name"": ""Apple"",  ""Price"": 1.20 },
    { ""Category"": ""Fruits"", ""Name"": ""Banana"", ""Price"": 0.80 },
    { ""Category"": ""Vegetables"", ""Name"": ""Carrot"", ""Price"": 0.50 },
    { ""Category"": ""Vegetables"", ""Name"": ""Lettuce"", ""Price"": 1.00 }
  ]
}";
        File.WriteAllText(jsonPath, jsonContent, Encoding.UTF8);

        // -----------------------------------------------------------------
        // 2. Build a template document that contains LINQ Reporting tags.
        // -----------------------------------------------------------------
        const string templatePath = "template.docx";
        var templateDoc = new Document();
        var builder = new DocumentBuilder(templateDoc);

        builder.Writeln("Report generated by Aspose.Words LINQ Reporting");
        builder.Writeln();

        // Outer foreach – groups of items by Category.
        builder.Writeln("<<foreach [group in model.Items.GroupBy(i => i.Category)]>>");
        builder.Writeln("Category: <<[group.Key]>>");
        builder.Writeln();

        // Inner foreach – items inside the current group.
        builder.Writeln("<<foreach [item in group]>>");
        builder.Writeln("- <<[item.Name]>> : $<<[item.Price]>>");
        builder.Writeln("<</foreach>>");
        builder.Writeln();

        // Close the outer foreach.
        builder.Writeln("<</foreach>>");

        // Save the template to disk.
        templateDoc.Save(templatePath);

        // -----------------------------------------------------------------
        // 3. Load the template and the JSON data source, then build the report.
        // -----------------------------------------------------------------
        var doc = new Document(templatePath);

        // Deserialize JSON into a strongly‑typed model.
        var model = JsonConvert.DeserializeObject<ReportModel>(jsonContent) ?? new ReportModel();

        var engine = new ReportingEngine();
        engine.BuildReport(doc, model, "model");

        // -----------------------------------------------------------------
        // 4. Save the generated report.
        // -----------------------------------------------------------------
        const string outputPath = "output.docx";
        doc.Save(outputPath);

        Console.WriteLine($"Report generated: {Path.GetFullPath(outputPath)}");
    }
}

// Root object that matches the JSON structure.
public class ReportModel
{
    public List<Item> Items { get; set; } = new();
}

// Individual item definition.
public class Item
{
    public string Category { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public double Price { get; set; }
}
