// ALL ATTEMPTS FAILED. Below is the last generated code.

using System;
using System.Drawing.Printing;
using Aspose.Words;
using Aspose.Words.Rendering;

class Program
{
    static void Main()
    {
        // Load the source document (replace with your actual file path).
        Document doc = new Document("InputDocument.docx");

        // Configure printer settings to use the built‑in "Microsoft Print to PDF" printer.
        PrinterSettings printerSettings = new PrinterSettings
        {
            PrinterName = "Microsoft Print to PDF",
            PrintRange = PrintRange.AllPages
        };

        // Create an Aspose.Words print document that integrates with the .NET printing framework.
        AsposeWordsPrintDocument printDoc = new AsposeWordsPrintDocument(doc);
        printDoc.PrinterSettings = printerSettings;

        // Optional: cache printer settings to reduce the first print call overhead.
        printDoc.CachePrinterSettings();

        // Print the document. The output will be a PDF file generated by the virtual printer.
        printDoc.Print();

        // At this point the PDF has been sent to the printer's output location
        // (usually the folder configured for "Microsoft Print to PDF").
        Console.WriteLine("Document sent to PDF printer.");
    }
}
