using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Comparing;

public class Program
{
    public static void Main()
    {
        // Create a folder for the batch comparison inputs and outputs.
        string inputDir = Path.Combine(Directory.GetCurrentDirectory(), "ComparisonBatch");
        Directory.CreateDirectory(inputDir);

        // Seed the folder with two pairs of documents that have differences.
        CreateSamplePair(inputDir, "Pair1", "First version of Pair1.", "Second version of Pair1 with changes.");
        CreateSamplePair(inputDir, "Pair2", "Initial content for Pair2.", "Modified content for Pair2 with extra line.");

        // Process each pair: compare the "_A" document with its corresponding "_B" document.
        foreach (string fileAPath in Directory.GetFiles(inputDir, "*_A.docx"))
        {
            string fileBPath = fileAPath.Replace("_A.docx", "_B.docx");
            if (!File.Exists(fileBPath))
                continue; // Skip if the matching B document is missing.

            // Load the two documents.
            Document docA = new Document(fileAPath);
            Document docB = new Document(fileBPath);

            // Perform comparison; revisions will be tracked in docA.
            docA.Compare(docB, "BatchComparer", DateTime.Now);

            // Count the revisions generated by the comparison.
            int revisionCount = docA.Revisions.Count;

            // Save the compared document with revisions.
            string resultPath = Path.Combine(
                inputDir,
                Path.GetFileNameWithoutExtension(fileAPath) + "_Compared.docx");
            docA.Save(resultPath);

            // Report the revision count to the console.
            Console.WriteLine($"{Path.GetFileName(fileAPath)} vs {Path.GetFileName(fileBPath)}: {revisionCount} revisions.");
        }
    }

    // Helper method to create a pair of documents with given contents.
    private static void CreateSamplePair(string folder, string pairName, string contentA, string contentB)
    {
        // Document A
        Document docA = new Document();
        DocumentBuilder builderA = new DocumentBuilder(docA);
        builderA.Writeln(contentA);
        string pathA = Path.Combine(folder, $"{pairName}_A.docx");
        docA.Save(pathA);

        // Document B
        Document docB = new Document();
        DocumentBuilder builderB = new DocumentBuilder(docB);
        builderB.Writeln(contentB);
        string pathB = Path.Combine(folder, $"{pairName}_B.docx");
        docB.Save(pathB);
    }
}
