using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Comparing;

public class Program
{
    public static void Main()
    {
        // Create the first version of a legal contract.
        Document contractV1 = new Document();
        DocumentBuilder builder1 = new DocumentBuilder(contractV1);
        builder1.Writeln("Legal Contract");
        builder1.Writeln("This agreement is made on the 1st of January 2023.");
        builder1.Writeln("The parties agree to the following terms:");
        builder1.Writeln("1. Confidentiality");
        builder1.Writeln("All confidential information shall be protected.");
        // Formatted paragraph (bold) that will be changed later.
        builder1.Font.Bold = true;
        builder1.Writeln("2. Termination");
        builder1.Font.Bold = false;
        builder1.Writeln("Either party may terminate with 30 days notice.");

        // Create the second version with content and formatting changes.
        Document contractV2 = new Document();
        DocumentBuilder builder2 = new DocumentBuilder(contractV2);
        builder2.Writeln("Legal Contract");
        builder2.Writeln("This agreement is made on the 1st of February 2023."); // Date changed.
        builder2.Writeln("The parties agree to the following terms:");
        builder2.Writeln("1. Confidentiality");
        builder2.Writeln("All confidential information shall be protected and not disclosed."); // Text changed.
        // Formatting change (italic instead of bold).
        builder2.Font.Italic = true;
        builder2.Writeln("2. Termination");
        builder2.Font.Italic = false;
        builder2.Writeln("Either party may terminate with 60 days notice."); // Text changed.

        // Configure comparison to ignore formatting changes.
        CompareOptions compareOptions = new CompareOptions
        {
            IgnoreFormatting = true
        };

        // Perform the comparison; revisions will be added to contractV1.
        contractV1.Compare(contractV2, "LegalTeam", DateTime.Now, compareOptions);

        // Count the revisions generated by the comparison.
        int revisionCount = contractV1.Revisions.Count;

        // Save the result document.
        string outputPath = Path.Combine(Directory.GetCurrentDirectory(), "ContractComparison.docx");
        contractV1.Save(outputPath);

        // Output a simple summary.
        Console.WriteLine($"Comparison completed. Revisions count: {revisionCount}");
    }
}
