using System;
using System.IO;
using Aspose.Words;
using Aspose.Words.Comparing;

public class Program
{
    public static void Main()
    {
        // Prepare output folder and file paths.
        string outputDir = "Output";
        Directory.CreateDirectory(outputDir);
        string originalPath = Path.Combine(outputDir, "Original.docx");
        string editedPath = Path.Combine(outputDir, "Edited.docx");
        string resultPath = Path.Combine(outputDir, "ComparedResult.docx");

        // Create the original document with some content.
        Document original = new Document();
        DocumentBuilder builderOriginal = new DocumentBuilder(original);
        builderOriginal.Writeln("This is the original document.");
        builderOriginal.Writeln("It contains some sample text.");
        original.Save(originalPath);

        // Create the edited document that has intentional differences.
        Document edited = new Document();
        DocumentBuilder builderEdited = new DocumentBuilder(edited);
        builderEdited.Writeln("This is the edited document."); // Modified line.
        builderEdited.Writeln("It contains some sample text."); // Same line.
        builderEdited.Writeln("Additional line added.");        // New line.
        edited.Save(editedPath);

        // Load the documents back from disk (ensures a realistic load scenario).
        Document docOriginal = new Document(originalPath);
        Document docEdited = new Document(editedPath);

        // Perform comparison only if both documents have no pre‑existing revisions.
        if (docOriginal.Revisions.Count == 0 && docEdited.Revisions.Count == 0)
        {
            docOriginal.Compare(docEdited, "Comparer", DateTime.Now);
        }

        // Output the number of revisions generated by the comparison.
        Console.WriteLine($"Revisions count: {docOriginal.Revisions.Count}");

        // Save the original document now containing revisions.
        docOriginal.Save(resultPath);
    }
}
